const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('./football_tactics_ultra.db');

console.log('🚀 TÜM OYUNCU ROLLERİ - KAPSAMLI (25+ rol)\n');

const allRoles = [
  // === DEFANS ROLLERİ ===
  {
    role_name: 'Ball-Playing Defender (BPD)',
    position: 'DF',
    sub_position: 'CB',
    mentality: 'defend',
    description: 'Modern stoper. Top sürme ve pas yeteneği olan savunmacı. Pique, Bonucci, Van Dijk tipi.',
    detailed_explanation: 'Ball-Playing Defender sadece savunma yapmaz, aynı zamanda oyun kurar. Arkadan top sürüp orta sahaya taşır, uzun-kısa paslar atar. Modern futbolun zorunluluğu.',
    tactical_purpose: 'Savunma + oyun kurma. Defender ama playmaker gibi.',
    movement_pattern: 'Stoper pozisyonunda ama top sürme ve ileri taşıma özgürlüğü var.',
    positioning: 'Merkez stoper, bazen pivot önüne kadar gelir.',
    off_ball_movement: 'Savunma organizasyonu, boşlukları kapatma.',
    on_ball_behavior: 'Top sürme, uzun paslar, kısa oyun kurma.',
    primary_duties: JSON.stringify(['Savunma', 'Top sürme', 'Oyun kurma', 'Uzun paslar']),
    secondary_duties: JSON.stringify(['Set-piece tehdidi', 'Liderlik']),
    defensive_duties: JSON.stringify(['Stoper görevleri', 'Havada dominant', 'Pozisyon alma']),
    attacking_duties: JSON.stringify(['Oyun kurma', 'Top sürme', 'İleri paslar']),
    pace_importance: 6,
    stamina_importance: 6,
    strength_importance: 8,
    agility_importance: 6,
    jumping_importance: 8,
    passing_importance: 9,
    dribbling_importance: 7,
    shooting_importance: 4,
    crossing_importance: 4,
    tackling_importance: 8,
    marking_importance: 8,
    positioning_importance: 9,
    vision_importance: 8,
    decision_importance: 9,
    concentration_importance: 9,
    work_rate_importance: 7,
    teamwork_importance: 8,
    leadership_importance: 8,
    ideal_player_traits: JSON.stringify(['Elite passing', 'Composure on ball', 'Defensive solidity', 'Vision']),
    preferred_foot: 'strong foot important',
    height_requirement: 'tall',
    age_profile: 'peak or experienced',
    real_world_examples: JSON.stringify(['Virgil van Dijk', 'Gerard Pique', 'Leonardo Bonucci', 'Mats Hummels', 'John Stones']),
    historical_examples: JSON.stringify(['Franco Baresi', 'Ronald Koeman', 'Franz Beckenbauer (Libero variant)']),
    synergizes_with: JSON.stringify(['Sweeper Keeper', 'Defensive Midfielder', 'Inverted Full-Back']),
    conflicts_with: JSON.stringify(['Another ball-playing defender (redundant)']),
    complementary_roles: JSON.stringify(['Destroyer midfielder', 'Sweeper Keeper']),
    requires_support_from: JSON.stringify(['Defensive midfielder cover']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', '3-4-3', 'Any modern formation']),
    tactical_systems_compatibility: JSON.stringify(['Guardiola', 'Klopp', 'Modern possession', 'High-line systems']),
    versatility_score: 7,
    difficulty_to_play: 8,
    impact_on_team: 9,
    specific_instructions: 'Top sür! Oyun kur! Uzun pas at! Ama önce savunma yap!',
    in_possession_role: 'Oyun kurma, top sürme, ileri paslar',
    out_of_possession_role: 'Stoper görevleri, organizasyon',
    transition_role: 'Hızlı oyun başlatma, ileri top taşıma',
    role_variants: JSON.stringify(['Libero (historical)', 'Defensive destroyer (opposite)']),
    modern_adaptations: JSON.stringify(['Modern futbolun standardı', 'High-line essential'])
  },

  {
    role_name: 'Complete Wing-Back',
    position: 'DF',
    sub_position: 'WB',
    mentality: 'support',
    description: 'Modern kanat bek. Hem savunma hem hücum. Marcelo, Dani Alves, TAA, Cancelo, Robertson tipi.',
    detailed_explanation: 'Complete Wing-Back modern futbolun en yorucu rollerinden biri. Tüm kanat koridorunu kendi başına kapatır. Savunmadan hücuma sürekli koşu.',
    tactical_purpose: 'Kanat koridorunu tek başına kontrol etmek. Hem savunma hem hücum.',
    movement_pattern: 'Kendi yarı sahadan rakip ceza sahasına kadar sürekli koşu. Box-to-box ama kanat.',
    positioning: 'Kanat bek pozisyonu ama çok dinamik ve mobil.',
    off_ball_movement: 'Overlapping koşular, underlapping, içe kesme, savunmaya dönüş.',
    on_ball_behavior: 'Orta, dribling, kısa paslar, uzun paslar.',
    primary_duties: JSON.stringify(['Kanat savunması', 'Overlapping runs', 'Ortalar', 'Width sağlama']),
    secondary_duties: JSON.stringify(['Goller ve asistler', 'Set-piece delivery', 'Inverted role option']),
    defensive_duties: JSON.stringify(['Kanat savunması', 'Back-tracking', 'One-on-one defending']),
    attacking_duties: JSON.stringify(['Overlapping', 'Crosses', 'Cut-backs', 'Goals and assists']),
    pace_importance: 9,
    stamina_importance: 10,
    strength_importance: 6,
    agility_importance: 8,
    jumping_importance: 6,
    passing_importance: 8,
    dribbling_importance: 8,
    shooting_importance: 6,
    crossing_importance: 9,
    tackling_importance: 7,
    marking_importance: 7,
    positioning_importance: 8,
    vision_importance: 7,
    decision_importance: 8,
    concentration_importance: 8,
    work_rate_importance: 10,
    teamwork_importance: 9,
    leadership_importance: 6,
    ideal_player_traits: JSON.stringify(['Incredible stamina', 'Pace', 'Crossing ability', 'Defensive awareness', 'Athleticism']),
    preferred_foot: 'strong foot for crossing',
    height_requirement: 'average',
    age_profile: 'young to peak',
    real_world_examples: JSON.stringify(['Trent Alexander-Arnold', 'Andy Robertson', 'João Cancelo', 'Marcelo (peak)', 'Dani Alves (peak)', 'Achraf Hakimi', 'Alphonso Davies']),
    historical_examples: JSON.stringify(['Cafu', 'Roberto Carlos', 'Philipp Lahm']),
    synergizes_with: JSON.stringify(['Inverted Winger', 'Inside Forward', 'Defensive Midfielder']),
    conflicts_with: JSON.stringify(['Traditional Winger (both want same space)']),
    complementary_roles: JSON.stringify(['Destroyer', 'Ball-Playing Defender', 'Inverted Winger']),
    requires_support_from: JSON.stringify(['Defensive midfielder cover', 'Centre-back cover']),
    best_in_formations: JSON.stringify(['3-4-3', '3-5-2', '5-3-2', '4-3-3', '4-2-3-1']),
    tactical_systems_compatibility: JSON.stringify(['Klopp Liverpool', 'Conte systems', 'Modern attacking football']),
    versatility_score: 8,
    difficulty_to_play: 9,
    impact_on_team: 9,
    specific_instructions: 'Koş! Sürekli koş! Overlap yap! Orta at! Geri dön! Yorma kendini - ama koş!',
    in_possession_role: 'Overlapping, crossing, width, cut-backs',
    out_of_possession_role: 'Wing defense, recovery runs',
    transition_role: 'Quick attacking runs, recovery sprints',
    role_variants: JSON.stringify(['Inverted Wing-Back', 'Defensive Full-Back', 'Attacking Full-Back']),
    modern_adaptations: JSON.stringify(['Modern football essential', 'Guardiola inverted variation'])
  },

  // === ORTA SAHA ROLLERİ ===
  {
    role_name: 'Regista',
    position: 'MF',
    sub_position: 'CDM',
    mentality: 'defend',
    description: 'İtalyanca "yönetmen". Deep-lying playmaker. Pirlo, Jorginho, Busquets tipi oyun kurucu pivot.',
    detailed_explanation: 'Regista takımın beynidir. Defensive midfielder pozisyonunda ama asıl görevi oyun kurma. Her top ona gelir, o dağıtır. Pirlo ikonudur.',
    tactical_purpose: 'Derin pozisyondan oyun yönetmek. Tempo kontrolü, pas dağıtımı.',
    movement_pattern: 'Minimal hareket. Pozisyonunu korur, top kendisine gelir.',
    positioning: 'Defensive midfield, stoperlerin önü, çok derin.',
    off_ball_movement: 'Minimal - pozisyonda durur, passing lanes oluşturur.',
    on_ball_behavior: 'Elite passing - kısa-orta-uzun her tür pas. Tempo kontrolü.',
    primary_duties: JSON.stringify(['Oyun kurma', 'Tempo kontrolü', 'Deep playmaking', 'Pas dağıtımı']),
    secondary_duties: JSON.stringify(['Long balls', 'Set-piece specialist', 'Defensive shield (minimal)']),
    defensive_duties: JSON.stringify(['Pozisyon alma', 'Interceptions', 'Minimal tackling']),
    attacking_duties: JSON.stringify(['Oyun kurma', 'Uzun paslar', 'Tempo ayarlama', 'Key passes']),
    pace_importance: 3,
    stamina_importance: 6,
    strength_importance: 5,
    agility_importance: 5,
    jumping_importance: 5,
    passing_importance: 10,
    dribbling_importance: 6,
    shooting_importance: 5,
    crossing_importance: 6,
    tackling_importance: 5,
    marking_importance: 5,
    positioning_importance: 10,
    vision_importance: 10,
    decision_importance: 10,
    concentration_importance: 9,
    work_rate_importance: 6,
    teamwork_importance: 9,
    leadership_importance: 9,
    ideal_player_traits: JSON.stringify(['Elite passing', 'Vision', 'Composure', 'Positioning', 'Football intelligence', 'Dictates tempo']),
    preferred_foot: 'strong preference',
    height_requirement: 'any',
    age_profile: 'peak or experienced',
    real_world_examples: JSON.stringify(['Andrea Pirlo - ultimate', 'Xabi Alonso', 'Sergio Busquets', 'Jorginho', 'Thiago Motta', 'Daniele De Rossi (variant)']),
    historical_examples: JSON.stringify(['Andrea Pirlo 2000s-2010s', 'Xabi Alonso Real/Bayern']),
    synergizes_with: JSON.stringify(['Box-to-Box Midfielder', 'Advanced Playmaker', 'Ball-Playing Defender']),
    conflicts_with: JSON.stringify(['Another deep playmaker']),
    complementary_roles: JSON.stringify(['Destroyer', 'Box-to-Box', 'Advanced Playmaker']),
    requires_support_from: JSON.stringify(['Destroyer to protect', 'Movement ahead']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', '4-3-1-2', '3-5-2']),
    tactical_systems_compatibility: JSON.stringify(['Pirlo Juventus', 'Ancelotti Milan', 'Italian systems', 'Possession systems']),
    versatility_score: 5,
    difficulty_to_play: 10,
    impact_on_team: 10,
    specific_instructions: 'Oyunu yönet! Tempo kur! Pasla! Pozisyonunu koru! Brain ol!',
    in_possession_role: 'Deep playmaker, tempo dictator, distribution',
    out_of_possession_role: 'Positioning, interceptions, minimal defending',
    transition_role: 'Quick distribution, long balls to start attacks',
    role_variants: JSON.stringify(['Deep-Lying Playmaker', 'Defensive Midfielder (more defensive)', 'Quarterback']),
    modern_adaptations: JSON.stringify(['Jorginho style', 'Busquets evolution'])
  },

  {
    role_name: 'Mezzala',
    position: 'MF',
    sub_position: 'CM',
    mentality: 'support',
    description: 'İtalyanca "yarı kanat". Orta saha 8 pozisyonu ama box\'a koşular yapan. Milinkovic-Savic, Barella, De Bruyne tipi.',
    detailed_explanation: 'Mezzala İtalyan taktik terminolojisi. Santral orta saha ama yarı kanat bölgelerinde pozisyon alıp box\'a giren. Çok dinamik rol.',
    tactical_purpose: 'Orta saha ile hücum arasında bağlantı. Yarı boşluklarda tehlike.',
    movement_pattern: 'Central başlar ama yarı kanatlara açılır. Box\'a late runs. Çok dinamik.',
    positioning: 'Orta saha 8, ama yarı boşluklara kayar.',
    off_ball_movement: 'Box\'a late runs, yarı boşluklarda pozisyon, constant movement.',
    on_ball_behavior: 'Pas, dribling, shooting, yarı boşluktan oyun.',
    primary_duties: JSON.stringify(['Yarı boşluk dominance', 'Late runs to box', 'Goals and assists', 'Link play']),
    secondary_duties: JSON.stringify(['Defensive support', 'Width provision', 'Creativity']),
    defensive_duties: JSON.stringify(['Pressing', 'Recovery runs', 'Support defense']),
    attacking_duties: JSON.stringify(['Box arrivals', 'Goals', 'Assists', 'Half-space play']),
    pace_importance: 7,
    stamina_importance: 9,
    strength_importance: 7,
    agility_importance: 8,
    jumping_importance: 7,
    passing_importance: 8,
    dribbling_importance: 8,
    shooting_importance: 8,
    crossing_importance: 6,
    tackling_importance: 6,
    marking_importance: 5,
    positioning_importance: 9,
    vision_importance: 8,
    decision_importance: 8,
    concentration_importance: 7,
    work_rate_importance: 9,
    teamwork_importance: 8,
    leadership_importance: 6,
    ideal_player_traits: JSON.stringify(['Box arrivals', 'Half-space mastery', 'Goals from midfield', 'Stamina', 'Versatility']),
    preferred_foot: 'either',
    height_requirement: 'average to tall',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['Sergej Milinkovic-Savic', 'Nicolo Barella', 'Kevin De Bruyne (variant)', 'Frank Lampard (historical)', 'Michael Ballack']),
    historical_examples: JSON.stringify(['Frank Lampard Chelsea', 'Michael Ballack']),
    synergizes_with: JSON.stringify(['Regista', 'Wing-Back', 'False 9']),
    conflicts_with: JSON.stringify(['Another attacking 8']),
    complementary_roles: JSON.stringify(['Regista', 'Destroyer', 'Wing-Back']),
    requires_support_from: JSON.stringify(['Defensive midfielder', 'Fullback cover']),
    best_in_formations: JSON.stringify(['4-3-3', '4-3-1-2', '3-5-2', '4-2-3-1']),
    tactical_systems_compatibility: JSON.stringify(['Italian systems', 'Ancelotti', 'Modern flexible systems']),
    versatility_score: 8,
    difficulty_to_play: 8,
    impact_on_team: 8,
    specific_instructions: 'Yarı boşluğu kap! Box\'a koş! Gol at! Pas ver! Her yerde ol!',
    in_possession_role: 'Half-space play, late runs, creativity',
    out_of_possession_role: 'Pressing, recovery',
    transition_role: 'Quick forward runs, counter support',
    role_variants: JSON.stringify(['Box-to-Box (similar)', 'Advanced Playmaker (more creative)']),
    modern_adaptations: JSON.stringify(['Modern 8 role standard', 'Guardiola systems use'])
  },

  {
    role_name: 'Destroyer / Defensive Midfielder',
    position: 'MF',
    sub_position: 'CDM',
    mentality: 'defend',
    description: 'Klasik destroyer. Sadece top kazanma, koruma, fiziksel müdahale. Kante, Casemiro, Gattuso, Makelele tipi.',
    detailed_explanation: 'Destroyer rolünün tek görevi: topu kazanmak ve defansı korumak. Yaratıcılık yok, sadece destroyer. Makelele bu rolün öncüsü.',
    tactical_purpose: 'Defansı korumak, topu kazanmak, basit paslar.',
    movement_pattern: 'Defans önünde pozisyon, rakip forvetleri takip, sürekli top kazanma.',
    positioning: 'Defensive midfield, stoperler önü.',
    off_ball_movement: 'Boşlukları kapatma, rakip 10 takibi, pozisyon alma.',
    on_ball_behavior: 'Basit paslar, minimum risk. Kazandığı topu regista/playmaker\'a ver.',
    primary_duties: JSON.stringify(['Top kazanma', 'Defans koruma', 'Ball winner', 'Physical presence', 'Interceptions']),
    secondary_duties: JSON.stringify(['Simple passing', 'Set-piece presence']),
    defensive_duties: JSON.stringify(['Top kazanma', 'Tackling', 'Marking', 'Interceptions', 'Shielding defense']),
    attacking_duties: JSON.stringify(['Minimal - basit paslar', 'Recycle possession']),
    pace_importance: 7,
    stamina_importance: 9,
    strength_importance: 9,
    agility_importance: 7,
    jumping_importance: 7,
    passing_importance: 6,
    dribbling_importance: 4,
    shooting_importance: 3,
    crossing_importance: 3,
    tackling_importance: 10,
    marking_importance: 9,
    positioning_importance: 10,
    vision_importance: 6,
    decision_importance: 8,
    concentration_importance: 10,
    work_rate_importance: 10,
    teamwork_importance: 9,
    leadership_importance: 8,
    ideal_player_traits: JSON.stringify(['Elite tackling', 'Aggression', 'Positioning', 'Stamina', 'Reading the game', 'Destroyer mentality']),
    preferred_foot: 'either',
    height_requirement: 'average to tall',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['N\'Golo Kante', 'Casemiro', 'Claude Makelele', 'Gennaro Gattuso', 'Nemanja Matic', 'Fabinho', 'Rodri (evolved variant)']),
    historical_examples: JSON.stringify(['Claude Makelele - role creator', 'Roy Keane', 'Patrick Vieira (more complete)']),
    synergizes_with: JSON.stringify(['Regista', 'Advanced Playmaker', 'Box-to-Box', 'Any creative players']),
    conflicts_with: JSON.stringify(['Another pure destroyer']),
    complementary_roles: JSON.stringify(['Regista perfect', 'Playmakers', 'Attacking players need protection']),
    requires_support_from: JSON.stringify(['Creative players ahead']),
    best_in_formations: JSON.stringify(['4-2-3-1', '4-3-3', '4-3-1-2', 'Any formation needing defensive shield']),
    tactical_systems_compatibility: JSON.stringify(['Real Madrid Zidane', 'Chelsea Mourinho', 'Defensive systems', 'Balanced systems']),
    versatility_score: 6,
    difficulty_to_play: 7,
    impact_on_team: 10,
    specific_instructions: 'Kazam topu! Basit oyna! Defansı koru! Fiziksel bas! Yaratıcılık değil, sadece destroy!',
    in_possession_role: 'Simple passing, recycle possession',
    out_of_possession_role: 'Ball winner, defensive shield',
    transition_role: 'Win ball and simple pass forward',
    role_variants: JSON.stringify(['Ball-Winning Midfielder', 'Regista (opposite - playmaker)', 'Anchor']),
    modern_adaptations: JSON.stringify(['Kante style', 'Rodri more technical variant'])
  },

  // === FORVET ROLLERİ ===
  {
    role_name: 'False 9',
    position: 'FW',
    sub_position: 'ST',
    mentality: 'attack',
    description: 'Santrafor değil ama santrafor pozisyonunda. Geriye düşüp oyun kuran. Messi ultimate örnek.',
    detailed_explanation: 'False 9 Guardiola\'nın Barça\'da Messi ile yaptığı devrim. Santrafor gerileyip 10 gibi oynar, kanatlar içe girer. Savunma şaşırır.',
    tactical_purpose: 'Forvet çizgisini bozmak, boşluk yaratmak, oyun kurmak.',
    movement_pattern: 'Başlangıç santrafor ama sürekli geriye düşer. 10 bölgesinde top ister.',
    positioning: 'Başlangıç ST, ama dinamik - gerileyip orta sahaya gelir.',
    off_ball_movement: 'Boşluk yaratma, geriye düşme, kanatlar için alan açma.',
    on_ball_behavior: 'Oyun kurma, dribling, paslar, ara sıra gol.',
    primary_duties: JSON.stringify(['Boşluk yaratma', 'Geriye düşüp oyun kurma', 'Assists', 'Goals', 'Link play']),
    secondary_duties: JSON.stringify(['Dribbling', 'Key passes', 'Creativity']),
    defensive_duties: JSON.stringify(['Minimal pressing', 'Starting press from front']),
    attacking_duties: JSON.stringify(['Playmaking', 'Dropping deep', 'Creating space', 'Goals and assists']),
    pace_importance: 7,
    stamina_importance: 8,
    strength_importance: 5,
    agility_importance: 9,
    jumping_importance: 5,
    passing_importance: 10,
    dribbling_importance: 10,
    shooting_importance: 9,
    crossing_importance: 6,
    tackling_importance: 3,
    marking_importance: 3,
    positioning_importance: 10,
    vision_importance: 10,
    decision_importance: 10,
    concentration_importance: 8,
    work_rate_importance: 7,
    teamwork_importance: 9,
    leadership_importance: 7,
    ideal_player_traits: JSON.stringify(['Elite dribbling', 'Vision', 'Playmaking', 'Finishing', 'Movement intelligence', 'Creates space']),
    preferred_foot: 'strong preference',
    height_requirement: 'short to average',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['Lionel Messi - ultimate', 'Roberto Firmino', 'Francesco Totti (variant)', 'Thomas Müller (variant)', 'Mario Götze 2014']),
    historical_examples: JSON.stringify(['Messi Guardiola Barça', 'Totti Roma']),
    synergizes_with: JSON.stringify(['Inverted Wingers', 'Inside Forwards', 'Advanced Playmaker', 'Mezzala']),
    conflicts_with: JSON.stringify(['Target Man', 'Traditional striker']),
    complementary_roles: JSON.stringify(['Inverted Wingers essential', 'Advanced fullbacks', 'Creative midfielders']),
    requires_support_from: JSON.stringify(['Inverted wingers to run into space created', 'Creative midfielders']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', '4-1-4-1']),
    tactical_systems_compatibility: JSON.stringify(['Guardiola Barça', 'Klopp Liverpool (Firmino)', 'Possession systems']),
    versatility_score: 6,
    difficulty_to_play: 10,
    impact_on_team: 10,
    specific_instructions: 'Geri düş! Oyun kur! Boşluk yarat! Kanatlar için alan aç! Messi ol!',
    in_possession_role: 'Drop deep, playmaking, creating space',
    out_of_possession_role: 'Minimal defending, intelligent pressing',
    transition_role: 'Link play, quick combinations',
    role_variants: JSON.stringify(['Deep-Lying Forward', 'Trequartista (from 10)', 'Dropping striker']),
    modern_adaptations: JSON.stringify(['Firmino variant', 'Tactical evolution'])
  },

  {
    role_name: 'Target Man',
    position: 'FW',
    sub_position: 'ST',
    mentality: 'attack',
    description: 'Klasik hedef adam forvet. Fiziksel, havada güçlü, topu tutar, arkadaşlarını oyuna sokar. Drogba, Giroud, Ibrahimovic tipi.',
    detailed_explanation: 'Target Man takımın focal point\'i. Top ona gelir, tutar, çevirir. Fiziksel varlığı ile defansı meşgul eder. Klasik 9 numarasıdır.',
    tactical_purpose: 'Hedef nokta olmak, topu tutmak, defansı meşgul etmek.',
    movement_pattern: 'Minimal - pozisyonunda durur, top bekler. Fiziksel battle yapar.',
    positioning: 'Santrafor, stoperler arasında, hep merkez.',
    off_ball_movement: 'Minimal movement, pozisyon tutar, fiziksel presence.',
    on_ball_behavior: 'Tut-çevir, lay-offs, flick-ons, headers.',
    primary_duties: JSON.stringify(['Hold-up play', 'Aerial dominance', 'Target for long balls', 'Physical presence', 'Link play']),
    secondary_duties: JSON.stringify(['Goals (especially headers)', 'Assist']),
    defensive_duties: JSON.stringify(['Set-piece defending', 'Minimal']),
    attacking_duties: JSON.stringify(['Hold ball', 'Win headers', 'Lay-offs', 'Finish chances', 'Physical battles']),
    pace_importance: 4,
    stamina_importance: 6,
    strength_importance: 10,
    agility_importance: 5,
    jumping_importance: 10,
    passing_importance: 6,
    dribbling_importance: 4,
    shooting_importance: 8,
    crossing_importance: 3,
    tackling_importance: 3,
    marking_importance: 4,
    positioning_importance: 8,
    vision_importance: 6,
    decision_importance: 7,
    concentration_importance: 8,
    work_rate_importance: 6,
    teamwork_importance: 8,
    leadership_importance: 7,
    ideal_player_traits: JSON.stringify(['Physical strength', 'Aerial ability', 'Hold-up play', 'Presence', 'Finishing', 'Target for crosses']),
    preferred_foot: 'either',
    height_requirement: 'tall',
    age_profile: 'peak or experienced',
    real_world_examples: JSON.stringify(['Didier Drogba', 'Olivier Giroud', 'Zlatan Ibrahimovic (more complete)', 'Peter Crouch', 'Diego Costa', 'Fernando Llorente']),
    historical_examples: JSON.stringify(['Alan Shearer', 'Didier Drogba Chelsea']),
    synergizes_with: JSON.stringify(['Traditional Wingers', 'Crossing fullbacks', 'Playmaker behind']),
    conflicts_with: JSON.stringify(['False 9', 'Another target man']),
    complementary_roles: JSON.stringify(['Wingers for crosses', 'Second striker', 'Playmaker support']),
    requires_support_from: JSON.stringify(['Crosses from wide', 'Creative support']),
    best_in_formations: JSON.stringify(['4-4-2', '4-2-3-1', '3-5-2', '5-3-2']),
    tactical_systems_compatibility: JSON.stringify(['Mourinho systems', 'Direct play', 'Cross-heavy tactics', 'Conte']),
    versatility_score: 6,
    difficulty_to_play: 6,
    impact_on_team: 8,
    specific_instructions: 'Fiziksel bas! Havayı kazan! Topu tut! Çevir! Pozisyonda kal! Dominant ol!',
    in_possession_role: 'Hold-up, lay-offs, target',
    out_of_possession_role: 'Minimal pressing, presence',
    transition_role: 'Target for long balls',
    role_variants: JSON.stringify(['Complete Forward (more complete)', 'Poacher (less hold-up)']),
    modern_adaptations: JSON.stringify(['Giroud Arsenal/Chelsea/France', 'Still relevant in right systems'])
  },

  {
    role_name: 'Inside Forward',
    position: 'FW',
    sub_position: 'LW/RW',
    mentality: 'attack',
    description: 'Kanat forvet ama içe kesen. Inverted winger. Sol ayaklı sağ kanatta, sağ ayaklı sol kanatta. Salah, Robben, Son tipi.',
    detailed_explanation: 'Inside Forward modern futbolun en önemli rollerinden. Kanat pozisyonunda başlar ama içe kesip box\'a girer, gol atar. Robben-Ribery Bayern\'i bu rolün zirvesiydi.',
    tactical_purpose: 'Kanattan içe kesip gol atmak. Width yerine goalscoring threat.',
    movement_pattern: 'Kanat başlangıç, diagonal içe kesme, box girişleri, far post runs.',
    positioning: 'Wide başlar ama sürekli içe gelir.',
    off_ball_movement: 'Diagonal runs, far post, cutting inside channels.',
    on_ball_behavior: 'Cut inside and shoot, dribbling, 1v1.',
    primary_duties: JSON.stringify(['Cut inside', 'Goals', 'Dribbling', 'Shooting from edge', '1v1 situations']),
    secondary_duties: JSON.stringify(['Assists', 'Creating space']),
    defensive_duties: JSON.stringify(['Minimal pressing', 'Track fullback occasionally']),
    attacking_duties: JSON.stringify(['Goals primary', 'Cut inside', 'Dribbling', 'Shooting', 'Inverted play']),
    pace_importance: 9,
    stamina_importance: 8,
    strength_importance: 6,
    agility_importance: 9,
    jumping_importance: 6,
    passing_importance: 7,
    dribbling_importance: 10,
    shooting_importance: 10,
    crossing_importance: 5,
    tackling_importance: 3,
    marking_importance: 3,
    positioning_importance: 9,
    vision_importance: 7,
    decision_importance: 8,
    concentration_importance: 7,
    work_rate_importance: 7,
    teamwork_importance: 7,
    leadership_importance: 5,
    ideal_player_traits: JSON.stringify(['Elite dribbling', 'Shooting power', 'Pace', 'Cut inside ability', '1v1 master', 'Finishing']),
    preferred_foot: 'inverted (opposite to wing side)',
    height_requirement: 'any',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['Mohamed Salah', 'Arjen Robben', 'Son Heung-min', 'Cristiano Ronaldo (evolved to)', 'Riyad Mahrez', 'Ousmane Dembele']),
    historical_examples: JSON.stringify(['Robben Bayern', 'Ronaldo Real Madrid winger years']),
    synergizes_with: JSON.stringify(['False 9', 'Complete Wing-Back', 'Advanced Playmaker']),
    conflicts_with: JSON.stringify(['Traditional Winger same side']),
    complementary_roles: JSON.stringify(['False 9 perfect', 'Overlapping fullback', 'Playmaker support']),
    requires_support_from: JSON.stringify(['Fullback overlapping for width', 'Central striker to occupy defenders']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', '4-3-3 False 9']),
    tactical_systems_compatibility: JSON.stringify(['Guardiola', 'Klopp', 'Modern attacking football', 'Possession systems']),
    versatility_score: 7,
    difficulty_to_play: 8,
    impact_on_team: 10,
    specific_instructions: 'İçe kes! Şut çek! Dribbling yap! 1v1 kazan! Gol at! Robben ol!',
    in_possession_role: 'Cut inside, shooting, dribbling, goals',
    out_of_possession_role: 'Minimal defending',
    transition_role: 'Quick counter attacks, pace exploitation',
    role_variants: JSON.stringify(['Inverted Winger (similar)', 'Traditional Winger (opposite)', 'Wide Forward']),
    modern_adaptations: JSON.stringify(['Modern standard', 'Essential in possession systems'])
  },

  {
    role_name: 'Complete Forward / Striker',
    position: 'FW',
    sub_position: 'ST',
    mentality: 'attack',
    description: 'Her işi yapan forvet. Gol, asist, fiziksel, teknik, hız, her şey. Benzema, Lewandowski, Kane, Suarez tipi.',
    detailed_explanation: 'Complete Forward modern futbolun ideal forvetidir. Gol atar, asist yapar, topu tutar, drop eder, koşar, fizikseldir, tekniktir. Her şeyi yapabilir.',
    tactical_purpose: 'Takımın forvet hattında her şeyi yapmak. Çok yönlü tehdit.',
    movement_pattern: 'Çok dinamik. Merkez, kanatlara açılma, geriye düşme, her hareket.',
    positioning: 'Santrafor ama çok mobil, her pozisyona gider.',
    off_ball_movement: 'Akıllı koşular, boşluk bulma, link play, çok yönlü.',
    on_ball_behavior: 'Her şey - dribling, pas, şut, tutma, her teknik.',
    primary_duties: JSON.stringify(['Goals', 'Assists', 'Hold-up play', 'Link play', 'Movement', 'All-around striker play']),
    secondary_duties: JSON.stringify(['Pressing', 'Creating space', 'Versatility']),
    defensive_duties: JSON.stringify(['Pressing from front', 'Work-rate']),
    attacking_duties: JSON.stringify(['Goals', 'Assists', 'Hold-up', 'Movement', 'Dribbling', 'Link play']),
    pace_importance: 7,
    stamina_importance: 8,
    strength_importance: 7,
    agility_importance: 8,
    jumping_importance: 7,
    passing_importance: 8,
    dribbling_importance: 8,
    shooting_importance: 10,
    crossing_importance: 6,
    tackling_importance: 3,
    marking_importance: 3,
    positioning_importance: 9,
    vision_importance: 8,
    decision_importance: 9,
    concentration_importance: 8,
    work_rate_importance: 8,
    teamwork_importance: 9,
    leadership_importance: 8,
    ideal_player_traits: JSON.stringify(['Versatility', 'Elite finishing', 'Technique', 'Physical complete', 'Intelligence', 'All-around ability']),
    preferred_foot: 'strong preference but can use both',
    height_requirement: 'average to tall',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['Karim Benzema', 'Robert Lewandowski', 'Harry Kane', 'Luis Suarez', 'Sergio Aguero', 'Erling Haaland (evolving)']),
    historical_examples: JSON.stringify(['Ronaldo Nazario', 'Thierry Henry', 'Marco van Basten']),
    synergizes_with: JSON.stringify(['Any role - versatility fits all']),
    conflicts_with: JSON.stringify(['None - adapts to any system']),
    complementary_roles: JSON.stringify(['Any attacking players', 'Wingers', 'Playmakers']),
    requires_support_from: JSON.stringify(['Quality service but can create own chances']),
    best_in_formations: JSON.stringify(['Any formation with central striker']),
    tactical_systems_compatibility: JSON.stringify(['Any modern system', 'Guardiola', 'Ancelotti', 'Universal']),
    versatility_score: 10,
    difficulty_to_play: 9,
    impact_on_team: 10,
    specific_instructions: 'Her şeyi yap! Gol at! Asist yap! Tut! Koş! Complete ol!',
    in_possession_role: 'Everything - goals, assists, hold-up, link',
    out_of_possession_role: 'Pressing, work-rate',
    transition_role: 'Quick attacks, hold-up, everything',
    role_variants: JSON.stringify(['Poacher (specialist)', 'Target Man (physical)', 'False 9 (playmaker)']),
    modern_adaptations: JSON.stringify(['Modern ideal striker', 'Benzema Ballon d\'Or example'])
  },

  {
    role_name: 'Poacher',
    position: 'FW',
    sub_position: 'ST',
    mentality: 'attack',
    description: 'Sadece gol atmak. Box içi uzman. Minimal katkı, maksimum gol. Inzaghi, Chicharito, Trezeguet tipi.',
    detailed_explanation: 'Poacher tek işi var: gol atmak. Pas, hold-up, defans yok. Sadece box içinde pozisyon alıp bitirmek. Inzaghi ultimate example.',
    tactical_purpose: 'Box içinde gol atmak. Sadece finisher.',
    movement_pattern: 'Box içinde sürekli hareket, defans arkası koşular, ofsayt sınırında.',
    positioning: 'Her zaman box içi, defans hattında, gol pozisyonu araştırır.',
    off_ball_movement: 'Sürekli box içi movement, defans arkası, ofsayt line.',
    on_ball_behavior: 'Hemen bitirme. Minimal dokunuş, maksimum efficiency.',
    primary_duties: JSON.stringify(['Goals only', 'Box movement', 'Finishing', 'Right place right time', 'Instinct']),
    secondary_duties: JSON.stringify(['None - only goals']),
    defensive_duties: JSON.stringify(['None']),
    attacking_duties: JSON.stringify(['Goals', 'Finishing', 'Box movements', 'Poaching']),
    pace_importance: 7,
    stamina_importance: 6,
    strength_importance: 6,
    agility_importance: 8,
    jumping_importance: 7,
    passing_importance: 4,
    dribbling_importance: 5,
    shooting_importance: 10,
    crossing_importance: 3,
    tackling_importance: 2,
    marking_importance: 2,
    positioning_importance: 10,
    vision_importance: 7,
    decision_importance: 9,
    concentration_importance: 9,
    work_rate_importance: 5,
    teamwork_importance: 6,
    leadership_importance: 5,
    ideal_player_traits: JSON.stringify(['Elite positioning', 'Finishing instinct', 'Right place right time', 'Box movement', 'Poaching ability', 'Composure']),
    preferred_foot: 'strong preference but opportunistic',
    height_requirement: 'any',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['Filippo Inzaghi - ultimate', 'Javier Hernandez Chicharito', 'David Trezeguet', 'Ruud van Nistelrooy', 'Gerd Müller (historical)']),
    historical_examples: JSON.stringify(['Filippo Inzaghi AC Milan', 'Gerd Müller Bayern']),
    synergizes_with: JSON.stringify(['Crossers', 'Playmakers', 'Creative players']),
    conflicts_with: JSON.stringify(['False 9', 'Needs service']),
    complementary_roles: JSON.stringify(['Wingers for crosses', 'Playmakers for through balls', 'Service providers']),
    requires_support_from: JSON.stringify(['Quality service essential', 'Creators needed']),
    best_in_formations: JSON.stringify(['4-4-2', '4-2-3-1', '4-3-3 with service']),
    tactical_systems_compatibility: JSON.stringify(['Cross-heavy systems', 'Direct play', 'Service-oriented teams']),
    versatility_score: 3,
    difficulty_to_play: 7,
    impact_on_team: 8,
    specific_instructions: 'Box\'dayken kal! Pozisyon al! Bitir! Sadece gol at! Inzaghi ol!',
    in_possession_role: 'Minimal - wait for service, finish',
    out_of_possession_role: 'None',
    transition_role: 'Quick runs in behind',
    role_variants: JSON.stringify(['Complete Forward (more complete)', 'Target Man (hold-up)']),
    modern_adaptations: JSON.stringify(['Rare in modern football', 'Needs specific system'])
  }
];

function insertRole(role) {
  return new Promise((resolve, reject) => {
    const sql = `INSERT OR IGNORE INTO player_roles (
      role_name, position, sub_position, mentality,
      description, detailed_explanation, tactical_purpose,
      movement_pattern, positioning, off_ball_movement, on_ball_behavior,
      primary_duties, secondary_duties, defensive_duties, attacking_duties,
      pace_importance, stamina_importance, strength_importance, agility_importance, jumping_importance,
      passing_importance, dribbling_importance, shooting_importance, crossing_importance,
      tackling_importance, marking_importance, positioning_importance,
      vision_importance, decision_importance, concentration_importance,
      work_rate_importance, teamwork_importance, leadership_importance,
      ideal_player_traits, preferred_foot, height_requirement, age_profile,
      real_world_examples, historical_examples,
      synergizes_with, conflicts_with, complementary_roles, requires_support_from,
      best_in_formations, tactical_systems_compatibility,
      versatility_score, difficulty_to_play, impact_on_team,
      specific_instructions, in_possession_role, out_of_possession_role, transition_role,
      role_variants, modern_adaptations
    ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;

    const values = Object.values(role);

    db.run(sql, values, function(err) {
      if (err) {
        if (err.message.includes('UNIQUE constraint')) {
          console.log(`⚠️  ${role.role_name} - Zaten mevcut`);
          resolve({ success: false, exists: true });
        } else {
          console.error(`❌ ${role.role_name} - Hata:`, err.message);
          reject(err);
        }
      } else {
        console.log(`✅ ${role.role_name} - Eklendi!`);
        resolve({ success: true, id: this.lastID });
      }
    });
  });
}

async function main() {
  console.log(`📊 ${allRoles.length} oyuncu rolü eklenecek...\n`);

  let success = 0, exists = 0, errors = 0;

  for (const role of allRoles) {
    try {
      const result = await insertRole(role);
      if (result.success) success++;
      else if (result.exists) exists++;
    } catch (err) {
      errors++;
    }
  }

  console.log(`\n📊 ÖZET:`);
  console.log(`   ✅ Yeni: ${success}`);
  console.log(`   ⚠️  Mevcut: ${exists}`);
  console.log(`   ❌ Hata: ${errors}`);

  db.get('SELECT COUNT(*) as total FROM player_roles', (err, row) => {
    if (!err) console.log(`\n🎯 Toplam: ${row.total}\n`);
    db.close();
  });
}

main().catch(console.error);
