const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('./football_tactics_ultra.db');

console.log('🚀 ÖNCELİKLİ MODERN ROLLER EKLENİYOR...\n');

const roles = [
  {
    role_name: 'Inverted Full-Back',
    position: 'DF',
    sub_position: 'LB/RB',
    mentality: 'support',
    description: 'Fullback tucks inside to midfield. Zinchenko Arsenal, Cancelo Man City.',
    detailed_explanation: 'Revolutionary 2024 role. FB moves to midfield in possession creating 3-2 shape.',
    tactical_purpose: 'Create extra midfielder. Form double pivot. Numerical superiority.',
    movement_pattern: 'Wide to central when in possession.',
    positioning: 'Hybrid FB-midfielder between CBs or alongside DM.',
    off_ball_movement: 'Movement into midfield zones. Return to width when needed.',
    on_ball_behavior: 'Excellent passing. Quick distribution. Buildup specialist.',
    primary_duties: JSON.stringify(['Invert to midfield', 'Form double pivot', 'Buildup']),
    secondary_duties: JSON.stringify(['Defensive cover', 'Ball progression']),
    defensive_duties: JSON.stringify(['Return to FB instantly', 'Cover central']),
    attacking_duties: JSON.stringify(['Buildup support', 'Create advantage']),
    pace_importance: 7,
    stamina_importance: 8,
    strength_importance: 6,
    agility_importance: 7,
    jumping_importance: 5,
    passing_importance: 8,
    dribbling_importance: 7,
    shooting_importance: 4,
    crossing_importance: 5,
    tackling_importance: 7,
    marking_importance: 7,
    positioning_importance: 9,
    vision_importance: 8,
    decision_importance: 9,
    concentration_importance: 8,
    work_rate_importance: 8,
    teamwork_importance: 9,
    leadership_importance: 6,
    ideal_player_traits: JSON.stringify(['Elite positioning', 'Intelligent', 'Great passer']),
    preferred_foot: 'either',
    height_requirement: 'average',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['Zinchenko Arsenal', 'Lewis-Skelly', 'Cancelo City']),
    historical_examples: JSON.stringify(['New role 2020+', 'Guardiola innovation']),
    synergizes_with: JSON.stringify(['BPD', 'Regista', 'Inside Forward']),
    conflicts_with: JSON.stringify(['Traditional Winger']),
    complementary_roles: JSON.stringify(['Regista', 'Ball-Playing CB']),
    requires_support_from: JSON.stringify(['DM partner', 'CB cover']),
    best_in_formations: JSON.stringify(['3-2-4-1', '4-3-3', '4-2-3-1']),
    tactical_systems_compatibility: JSON.stringify(['Arteta Arsenal', 'Guardiola City']),
    versatility_score: 8,
    difficulty_to_play: 9,
    impact_on_team: 9,
    specific_instructions: 'Move to midfield when possession. Form double pivot. Return when lost.',
    in_possession_role: 'Invert to midfield buildup',
    out_of_possession_role: 'Return to fullback shape',
    transition_role: 'Quick positioning shift',
    role_variants: JSON.stringify(['Pure inverted', 'Hybrid inverted']),
    modern_adaptations: JSON.stringify(['Essential 2024', 'Arsenal mainstream'])
  },
  {
    role_name: 'Box-to-Box Midfielder',
    position: 'MF',
    sub_position: 'CM',
    mentality: 'support',
    description: 'Complete midfielder covering entire pitch. Gerrard, Lampard, Bellingham.',
    detailed_explanation: 'Box-to-Box everywhere! Complete midfielder presence in all phases.',
    tactical_purpose: 'Cover entire midfield. Attack and defend equally.',
    movement_pattern: 'Constant movement between both penalty boxes.',
    positioning: 'Central midfield with freedom to roam.',
    off_ball_movement: 'Late runs into box. Constant tracking back.',
    on_ball_behavior: 'Complete skillset: passing, shooting, dribbling.',
    primary_duties: JSON.stringify(['Box-to-box coverage', 'Late runs', 'Goals and assists']),
    secondary_duties: JSON.stringify(['Leadership', 'Set-pieces', 'Ball winning']),
    defensive_duties: JSON.stringify(['Track back', 'Tackle', 'Cover spaces']),
    attacking_duties: JSON.stringify(['Late runs', 'Goals', 'Assists', 'Link play']),
    pace_importance: 7,
    stamina_importance: 10,
    strength_importance: 7,
    agility_importance: 7,
    jumping_importance: 7,
    passing_importance: 8,
    dribbling_importance: 7,
    shooting_importance: 7,
    crossing_importance: 6,
    tackling_importance: 7,
    marking_importance: 7,
    positioning_importance: 8,
    vision_importance: 7,
    decision_importance: 8,
    concentration_importance: 8,
    work_rate_importance: 10,
    teamwork_importance: 9,
    leadership_importance: 8,
    ideal_player_traits: JSON.stringify(['Incredible stamina', 'Complete skillset', 'Elite work-rate']),
    preferred_foot: 'strong',
    height_requirement: 'average-tall',
    age_profile: 'peak physical condition',
    real_world_examples: JSON.stringify(['Steven Gerrard', 'Frank Lampard', 'Jude Bellingham', 'Leon Goretzka']),
    historical_examples: JSON.stringify(['Bryan Robson', 'Roy Keane', 'Patrick Vieira']),
    synergizes_with: JSON.stringify(['Regista', 'Ball-Playing CB', 'Complete Forward']),
    conflicts_with: JSON.stringify(['Another box-to-box - redundant']),
    complementary_roles: JSON.stringify(['Regista', 'Destroyer', 'Inside Forward']),
    requires_support_from: JSON.stringify(['Defensive midfielder']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', '4-4-2', 'Any midfield three']),
    tactical_systems_compatibility: JSON.stringify(['Modern balanced', 'Klopp system', 'Universal']),
    versatility_score: 10,
    difficulty_to_play: 8,
    impact_on_team: 9,
    specific_instructions: 'Cover everything! Attack and defend boxes. Never stop moving.',
    in_possession_role: 'Link play, late runs, passing options everywhere',
    out_of_possession_role: 'Defensive coverage, tackling, tracking runners',
    transition_role: 'Quick transitions both directions, energy critical',
    role_variants: JSON.stringify(['More attacking focus', 'More defensive', 'Balanced complete']),
    modern_adaptations: JSON.stringify(['Modern football staple', 'Physical demands increased'])
  },
  {
    role_name: 'Shadow Striker',
    position: 'MF',
    sub_position: 'CAM/SS',
    mentality: 'attack',
    description: 'Second striker making runs from deep. Thomas Muller, Bruno Fernandes.',
    detailed_explanation: 'Shadow Striker makes late runs from midfield. Behind main striker finding spaces.',
    tactical_purpose: 'Late runs into box. Link striker to midfield. Score goals from deep.',
    movement_pattern: 'Drops deep then bursts into box with late runs.',
    positioning: 'Between midfield and striker. Constantly moving off the ball.',
    off_ball_movement: 'Late runs are crucial. Find spaces between defensive lines.',
    on_ball_behavior: 'Quick passing, clinical shooting, intelligent link play.',
    primary_duties: JSON.stringify(['Late runs into box', 'Goals', 'Link striker to midfield']),
    secondary_duties: JSON.stringify(['Assists', 'Pressing from front', 'Set-piece threat']),
    defensive_duties: JSON.stringify(['Minimal defensive work', 'Press from front only']),
    attacking_duties: JSON.stringify(['Goals primary focus', 'Late runs', 'Link play']),
    pace_importance: 7,
    stamina_importance: 8,
    strength_importance: 6,
    agility_importance: 8,
    jumping_importance: 6,
    passing_importance: 7,
    dribbling_importance: 7,
    shooting_importance: 8,
    crossing_importance: 5,
    tackling_importance: 4,
    marking_importance: 4,
    positioning_importance: 9,
    vision_importance: 8,
    decision_importance: 9,
    concentration_importance: 7,
    work_rate_importance: 8,
    teamwork_importance: 8,
    leadership_importance: 6,
    ideal_player_traits: JSON.stringify(['Anticipation elite', 'Clinical finishing', 'Off the ball movement']),
    preferred_foot: 'strong',
    height_requirement: 'average',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['Thomas Muller', 'Bruno Fernandes', 'Antoine Griezmann', 'Dele Alli prime']),
    historical_examples: JSON.stringify(['Modern role evolution', 'No classical equivalent']),
    synergizes_with: JSON.stringify(['Complete Forward', 'Target Man', 'False 9']),
    conflicts_with: JSON.stringify(['Another shadow striker', 'Traditional 10']),
    complementary_roles: JSON.stringify(['Target Man', 'Deep-Lying Forward']),
    requires_support_from: JSON.stringify(['Main striker to link with']),
    best_in_formations: JSON.stringify(['4-2-3-1', '4-4-2 diamond', '4-3-1-2', '3-4-1-2']),
    tactical_systems_compatibility: JSON.stringify(['Bayern Muller system', 'Modern 10 evolution']),
    versatility_score: 6,
    difficulty_to_play: 7,
    impact_on_team: 8,
    specific_instructions: 'Find spaces between lines! Make late runs! Shoot on sight!',
    in_possession_role: 'Link striker, find pockets of space, create chances',
    out_of_possession_role: 'Press from front, minimal defensive duties',
    transition_role: 'Quick runs into space when ball won',
    role_variants: JSON.stringify(['More creative playmaker', 'More goalscoring focus']),
    modern_adaptations: JSON.stringify(['Modern number 10 evolution', 'Goals priority'])
  },
  {
    role_name: 'Attacking Wing-Back',
    position: 'DF',
    sub_position: 'WB',
    mentality: 'attack',
    description: 'Wing-back almost a winger. Hakimi, Alphonso Davies, Theo Hernandez.',
    detailed_explanation: 'Attacking wing-back spends most time in opposition half. Pace critical.',
    tactical_purpose: 'Provide width in attack. Stretch opposition. Crosses and goals.',
    movement_pattern: 'Very high and wide. Overlaps constantly.',
    positioning: 'Almost winger position in attack. Touchline hugger.',
    off_ball_movement: 'Constant overlaps. Sprint in behind. Recovery runs.',
    on_ball_behavior: 'Dribbling, crossing, pace. Occasional shooting.',
    primary_duties: JSON.stringify(['Width in attack', 'Overlaps', 'Crosses', 'Stretch play']),
    secondary_duties: JSON.stringify(['Goals', 'Cut inside', 'Press high']),
    defensive_duties: JSON.stringify(['Recovery runs', 'Last man back', 'Cover wide']),
    attacking_duties: JSON.stringify(['Width primary', 'Crosses', 'Overlaps', 'Goals']),
    pace_importance: 10,
    stamina_importance: 10,
    strength_importance: 6,
    agility_importance: 8,
    jumping_importance: 6,
    passing_importance: 6,
    dribbling_importance: 8,
    shooting_importance: 6,
    crossing_importance: 9,
    tackling_importance: 6,
    marking_importance: 6,
    positioning_importance: 7,
    vision_importance: 6,
    decision_importance: 7,
    concentration_importance: 7,
    work_rate_importance: 10,
    teamwork_importance: 7,
    leadership_importance: 5,
    ideal_player_traits: JSON.stringify(['Elite pace', 'Incredible stamina', 'Crossing ability']),
    preferred_foot: 'depends on side',
    height_requirement: 'any',
    age_profile: 'young peak speed',
    real_world_examples: JSON.stringify(['Achraf Hakimi', 'Alphonso Davies', 'Theo Hernandez', 'Pedro Porro']),
    historical_examples: JSON.stringify(['Dani Alves', 'Marcelo', 'Cafu']),
    synergizes_with: JSON.stringify(['Wide CB for cover', 'Target man', 'Inside forward opposite']),
    conflicts_with: JSON.stringify(['Traditional winger same side']),
    complementary_roles: JSON.stringify(['Wide CB', 'Inside Forward', 'Target Man']),
    requires_support_from: JSON.stringify(['CB cover', 'Midfield cover']),
    best_in_formations: JSON.stringify(['3-4-3', '3-5-2', '5-2-3', '3-4-2-1']),
    tactical_systems_compatibility: JSON.stringify(['Conte', 'Modern wing-back systems']),
    versatility_score: 6,
    difficulty_to_play: 7,
    impact_on_team: 8,
    specific_instructions: 'Stay very wide! Overlap constantly! Sprint back when lost possession!',
    in_possession_role: 'Winger essentially. Width and crosses.',
    out_of_possession_role: 'Sprint back to defense. Recovery critical.',
    transition_role: 'Quick transitions. Pace advantage both ways.',
    role_variants: JSON.stringify(['Pure width', 'Inverted attacking', 'Balanced']),
    modern_adaptations: JSON.stringify(['Pace more critical', 'Almost winger role now'])
  },
  {
    role_name: 'Anchor Man',
    position: 'MF',
    sub_position: 'DM',
    mentality: 'defend',
    description: 'Pure holding midfielder. Casemiro, Rodri, Fabinho, N Golo Kante.',
    detailed_explanation: 'Anchor man sits deepest. Protects defense. Minimal forward movement.',
    tactical_purpose: 'Shield defense. Break up play. Recycling possession.',
    movement_pattern: 'Minimal movement. Stay in front of defense.',
    positioning: 'Deepest midfielder. Between center-backs often.',
    off_ball_movement: 'Minimal. Position holding.',
    on_ball_behavior: 'Simple passing. Recycle possession. Safety first.',
    primary_duties: JSON.stringify(['Shield defense', 'Break up attacks', 'Simple passing']),
    secondary_duties: JSON.stringify(['Cover CBs', 'Recycle ball', 'Discipline']),
    defensive_duties: JSON.stringify(['Tackles', 'Interceptions', 'Positioning', 'Protect']),
    attacking_duties: JSON.stringify(['Minimal', 'Simple passes only', 'Stay back']),
    pace_importance: 5,
    stamina_importance: 7,
    strength_importance: 8,
    agility_importance: 6,
    jumping_importance: 7,
    passing_importance: 7,
    dribbling_importance: 4,
    shooting_importance: 3,
    crossing_importance: 3,
    tackling_importance: 9,
    marking_importance: 8,
    positioning_importance: 10,
    vision_importance: 7,
    decision_importance: 9,
    concentration_importance: 9,
    work_rate_importance: 8,
    teamwork_importance: 9,
    leadership_importance: 8,
    ideal_player_traits: JSON.stringify(['Elite positioning', 'Tackling', 'Discipline', 'Concentration']),
    preferred_foot: 'strong',
    height_requirement: 'tall preferred',
    age_profile: 'peak or experience',
    real_world_examples: JSON.stringify(['Casemiro', 'Rodri', 'Fabinho', 'N Golo Kante', 'Declan Rice']),
    historical_examples: JSON.stringify(['Claude Makelele', 'Sergio Busquets', 'Javier Mascherano']),
    synergizes_with: JSON.stringify(['Box-to-box MF', 'Ball-playing CB', 'Advanced playmakers']),
    conflicts_with: JSON.stringify(['Another anchor redundant']),
    complementary_roles: JSON.stringify(['Box-to-box', 'Mezzala', 'Regista']),
    requires_support_from: JSON.stringify(['CB partnership']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1 single pivot', 'Any with single DM']),
    tactical_systems_compatibility: JSON.stringify(['Modern defensive solidity', 'Guardiola', 'Universal']),
    versatility_score: 5,
    difficulty_to_play: 8,
    impact_on_team: 9,
    specific_instructions: 'Hold position! Simple passes! Break up attacks! Never leave position!',
    in_possession_role: 'Simple passing. Recycle ball. Safe options.',
    out_of_possession_role: 'Shield defense. Positioning elite. Read game.',
    transition_role: 'Quick to defensive position. Slow attacks down.',
    role_variants: JSON.stringify(['Pure destroyer', 'More passing', 'Balanced holder']),
    modern_adaptations: JSON.stringify(['Passing ability more important', 'Still essential role'])
  }
];

let completed = 0;
const stmt = db.prepare(`INSERT OR IGNORE INTO player_roles (
  role_name, position, sub_position, mentality, description, detailed_explanation,
  tactical_purpose, movement_pattern, positioning, off_ball_movement, on_ball_behavior,
  primary_duties, secondary_duties, defensive_duties, attacking_duties,
  pace_importance, stamina_importance, strength_importance, agility_importance, jumping_importance,
  passing_importance, dribbling_importance, shooting_importance, crossing_importance,
  tackling_importance, marking_importance, positioning_importance,
  vision_importance, decision_importance, concentration_importance,
  work_rate_importance, teamwork_importance, leadership_importance,
  ideal_player_traits, preferred_foot, height_requirement, age_profile,
  real_world_examples, historical_examples,
  synergizes_with, conflicts_with, complementary_roles, requires_support_from,
  best_in_formations, tactical_systems_compatibility,
  versatility_score, difficulty_to_play, impact_on_team,
  specific_instructions, in_possession_role, out_of_possession_role, transition_role,
  role_variants, modern_adaptations
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);

roles.forEach((r, i) => {
  stmt.run(
    r.role_name, r.position, r.sub_position, r.mentality, r.description, r.detailed_explanation,
    r.tactical_purpose, r.movement_pattern, r.positioning, r.off_ball_movement, r.on_ball_behavior,
    r.primary_duties, r.secondary_duties, r.defensive_duties, r.attacking_duties,
    r.pace_importance, r.stamina_importance, r.strength_importance, r.agility_importance, r.jumping_importance,
    r.passing_importance, r.dribbling_importance, r.shooting_importance, r.crossing_importance,
    r.tackling_importance, r.marking_importance, r.positioning_importance,
    r.vision_importance, r.decision_importance, r.concentration_importance,
    r.work_rate_importance, r.teamwork_importance, r.leadership_importance,
    r.ideal_player_traits, r.preferred_foot, r.height_requirement, r.age_profile,
    r.real_world_examples, r.historical_examples,
    r.synergizes_with, r.conflicts_with, r.complementary_roles, r.requires_support_from,
    r.best_in_formations, r.tactical_systems_compatibility,
    r.versatility_score, r.difficulty_to_play, r.impact_on_team,
    r.specific_instructions, r.in_possession_role, r.out_of_possession_role, r.transition_role,
    r.role_variants, r.modern_adaptations,
    (err) => {
      if (err) {
        console.log(`❌ ${r.role_name} - Hata: ${err.message}`);
      } else {
        completed++;
        console.log(`✅ ${completed}/5: ${r.role_name} eklendi!`);
      }
    }
  );
});

stmt.finalize(() => {
  console.log(`\n🎯 ${completed}/5 öncelikli rol başarıyla eklendi!`);
  db.close();
});
