const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('./football_tactics_ultra.db');

console.log('🚀 7 EK MODERN ROL EKLENİYOR...\n');

const roles = [
  {
    role_name: 'Roaming Playmaker',
    position: 'MF',
    sub_position: 'CAM/CM',
    mentality: 'support',
    description: 'Free roaming creator. Kevin De Bruyne, Luka Modric, Martin Odegaard.',
    detailed_explanation: 'Roaming playmaker has complete freedom to create. Drifts anywhere finding space.',
    tactical_purpose: 'Creative hub. Find spaces. Unlock defenses with passes.',
    movement_pattern: 'Complete freedom. Drifts wide, deep, forward.',
    positioning: 'No fixed position. Intelligent roaming.',
    off_ball_movement: 'Constant movement finding pockets.',
    on_ball_behavior: 'Elite passing. Vision. Through balls. Key passes.',
    primary_duties: JSON.stringify(['Create chances', 'Through balls', 'Key passes', 'Vision']),
    secondary_duties: JSON.stringify(['Goals', 'Assists', 'Ball carrying']),
    defensive_duties: JSON.stringify(['Minimal', 'Press intelligently']),
    attacking_duties: JSON.stringify(['Creation primary', 'Assists', 'Unlock defenses']),
    pace_importance: 6,
    stamina_importance: 8,
    strength_importance: 5,
    agility_importance: 8,
    jumping_importance: 4,
    passing_importance: 10,
    dribbling_importance: 8,
    shooting_importance: 7,
    crossing_importance: 7,
    tackling_importance: 4,
    marking_importance: 3,
    positioning_importance: 9,
    vision_importance: 10,
    decision_importance: 10,
    concentration_importance: 8,
    work_rate_importance: 7,
    teamwork_importance: 8,
    leadership_importance: 7,
    ideal_player_traits: JSON.stringify(['Elite vision', 'Passing genius', 'Intelligence', 'Creativity']),
    preferred_foot: 'strong',
    height_requirement: 'any',
    age_profile: 'peak intelligence',
    real_world_examples: JSON.stringify(['Kevin De Bruyne', 'Luka Modric', 'Martin Odegaard', 'Bernardo Silva']),
    historical_examples: JSON.stringify(['Zinedine Zidane', 'Andres Iniesta', 'Andrea Pirlo advanced']),
    synergizes_with: JSON.stringify(['Anchor man', 'Inside forwards', 'Complete striker']),
    conflicts_with: JSON.stringify(['Another roaming playmaker', 'Traditional 10']),
    complementary_roles: JSON.stringify(['Anchor man', 'Box-to-box', 'Inside forward']),
    requires_support_from: JSON.stringify(['Defensive midfielder for freedom']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', '4-3-2-1', 'Any flexible']),
    tactical_systems_compatibility: JSON.stringify(['Man City De Bruyne', 'Real Madrid Modric', 'Arsenal Odegaard']),
    versatility_score: 9,
    difficulty_to_play: 9,
    impact_on_team: 10,
    specific_instructions: 'Complete freedom! Find spaces! Create! Through balls! Vision!',
    in_possession_role: 'Creative hub. Find spaces. Unlock defense.',
    out_of_possession_role: 'Intelligent pressing. Minimal defensive work.',
    transition_role: 'Quick transition passes. Vision critical.',
    role_variants: JSON.stringify(['More creative', 'More direct', 'Deep playmaker']),
    modern_adaptations: JSON.stringify(['Essential modern role', 'Freedom increased'])
  },
  {
    role_name: 'Pressing Forward',
    position: 'FW',
    sub_position: 'ST/CF',
    mentality: 'attack',
    description: 'Press-focused striker. Roberto Firmino, Gabriel Jesus, Diogo Jota.',
    detailed_explanation: 'Pressing forward leads defensive press. Work-rate more than goals.',
    tactical_purpose: 'Lead press. Trigger pressing traps. Link play.',
    movement_pattern: 'Constant pressing movements. Trigger press.',
    positioning: 'Striker position but focuses on pressing triggers.',
    off_ball_movement: 'Pressing runs. Closing passing lanes.',
    on_ball_behavior: 'Link play. Quick passing. Intelligent hold-up.',
    primary_duties: JSON.stringify(['Lead press', 'Trigger traps', 'Link play', 'Work-rate']),
    secondary_duties: JSON.stringify(['Goals secondary', 'Assists', 'Cover']),
    defensive_duties: JSON.stringify(['Lead press primary duty', 'Close lanes', 'High intensity']),
    attacking_duties: JSON.stringify(['Link play', 'Hold-up', 'Goals secondary']),
    pace_importance: 7,
    stamina_importance: 10,
    strength_importance: 7,
    agility_importance: 7,
    jumping_importance: 6,
    passing_importance: 7,
    dribbling_importance: 6,
    shooting_importance: 6,
    crossing_importance: 4,
    tackling_importance: 6,
    marking_importance: 7,
    positioning_importance: 8,
    vision_importance: 7,
    decision_importance: 9,
    concentration_importance: 9,
    work_rate_importance: 10,
    teamwork_importance: 10,
    leadership_importance: 7,
    ideal_player_traits: JSON.stringify(['Elite work-rate', 'Team player', 'Intelligence', 'Stamina']),
    preferred_foot: 'any',
    height_requirement: 'average',
    age_profile: 'peak fitness',
    real_world_examples: JSON.stringify(['Roberto Firmino', 'Gabriel Jesus', 'Diogo Jota', 'Alexis Sanchez prime']),
    historical_examples: JSON.stringify(['Modern role post-2015', 'Klopp innovation']),
    synergizes_with: JSON.stringify(['Inside forwards', 'High pressing system', 'Gegenpress']),
    conflicts_with: JSON.stringify(['Target man', 'Poacher']),
    complementary_roles: JSON.stringify(['Inside forward', 'Box-to-box', 'High press']),
    requires_support_from: JSON.stringify(['Wide forwards for goals']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', 'Any pressing system']),
    tactical_systems_compatibility: JSON.stringify(['Klopp Liverpool', 'Guardiola', 'High press systems']),
    versatility_score: 7,
    difficulty_to_play: 8,
    impact_on_team: 9,
    specific_instructions: 'Press constantly! Trigger traps! Team first! Link play!',
    in_possession_role: 'Link play. Hold-up. Quick passing.',
    out_of_possession_role: 'Lead press. Trigger pressing traps. Intensity.',
    transition_role: 'Quick press on turnovers. First defender.',
    role_variants: JSON.stringify(['More pressing', 'More goals', 'Balanced']),
    modern_adaptations: JSON.stringify(['Essential for high press', 'Klopp made mainstream'])
  },
  {
    role_name: 'Wide Centre-Back',
    position: 'DF',
    sub_position: 'CB',
    mentality: 'defend',
    description: 'CB in back three. Alessandro Bastoni, Josko Gvardiol.',
    detailed_explanation: 'Wide CB in back 3. More freedom to carry ball forward and cover wide.',
    tactical_purpose: 'Back 3 wide defender. Cover wide. Ball progression.',
    movement_pattern: 'Wider positioning. Step out with ball.',
    positioning: 'LCB or RCB in back 3 formation.',
    off_ball_movement: 'Cover wide channels. Step up.',
    on_ball_behavior: 'Ball carrying. Progressive passing. Step forward.',
    primary_duties: JSON.stringify(['Defend wide in 3', 'Ball progression', 'Cover channels']),
    secondary_duties: JSON.stringify(['Ball carrying', 'Overlaps', 'Buildup']),
    defensive_duties: JSON.stringify(['Defend 1v1 wide', 'Cover channels', 'Positioning']),
    attacking_duties: JSON.stringify(['Ball carrying', 'Step forward', 'Overlaps']),
    pace_importance: 7,
    stamina_importance: 7,
    strength_importance: 8,
    agility_importance: 7,
    jumping_importance: 8,
    passing_importance: 7,
    dribbling_importance: 6,
    shooting_importance: 4,
    crossing_importance: 5,
    tackling_importance: 8,
    marking_importance: 8,
    positioning_importance: 9,
    vision_importance: 6,
    decision_importance: 8,
    concentration_importance: 9,
    work_rate_importance: 7,
    teamwork_importance: 9,
    leadership_importance: 7,
    ideal_player_traits: JSON.stringify(['Pace for CB', 'Ball playing', '1v1 defending', 'Modern CB']),
    preferred_foot: 'left for LCB right for RCB',
    height_requirement: 'tall',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['Alessandro Bastoni', 'Josko Gvardiol', 'Ben White', 'Gabriel Magalhaes']),
    historical_examples: JSON.stringify(['Modern role', 'Back 3 evolution']),
    synergizes_with: JSON.stringify(['Central CB', 'Wing-backs', 'Sweeper keeper']),
    conflicts_with: JSON.stringify(['Traditional CB pairs']),
    complementary_roles: JSON.stringify(['Central CB', 'Wing-back', 'Anchor man']),
    requires_support_from: JSON.stringify(['Central CB partner', 'Wing-back cover']),
    best_in_formations: JSON.stringify(['3-4-3', '3-5-2', '5-2-3', 'Any back 3']),
    tactical_systems_compatibility: JSON.stringify(['Conte', 'Tuchel', 'Modern back 3']),
    versatility_score: 6,
    difficulty_to_play: 7,
    impact_on_team: 8,
    specific_instructions: 'Defend wide channel! Carry ball forward! Cover wing-back!',
    in_possession_role: 'Ball progression. Step forward with ball.',
    out_of_possession_role: 'Defend wide 1v1. Cover channels.',
    transition_role: 'Quick recovery. Step out to press.',
    role_variants: JSON.stringify(['More attacking', 'More defensive', 'Balanced']),
    modern_adaptations: JSON.stringify(['Essential for back 3', 'Ball playing crucial'])
  },
  {
    role_name: 'Inverted Winger',
    position: 'FW',
    sub_position: 'LW/RW',
    mentality: 'attack',
    description: 'Winger cuts inside to shoot. Arjen Robben, Bukayo Saka, Mohamed Salah.',
    detailed_explanation: 'Inverted winger plays on opposite foot. Cuts inside to shoot and create.',
    tactical_purpose: 'Cut inside. Shoot. Create angles. Overload central areas.',
    movement_pattern: 'Start wide, cut inside constantly.',
    positioning: 'Wide start, narrow when attacking.',
    off_ball_movement: 'Diagonal runs inside. Find shooting positions.',
    on_ball_behavior: 'Dribble inside. Shoot. Through balls central.',
    primary_duties: JSON.stringify(['Cut inside', 'Shoot', 'Goals', 'Dribbling']),
    secondary_duties: JSON.stringify(['Assists', 'Through balls', 'Width sometimes']),
    defensive_duties: JSON.stringify(['Minimal', 'Track back sometimes', 'Press']),
    attacking_duties: JSON.stringify(['Goals primary', 'Cut inside', 'Shoot', 'Create']),
    pace_importance: 9,
    stamina_importance: 8,
    strength_importance: 6,
    agility_importance: 9,
    jumping_importance: 5,
    passing_importance: 7,
    dribbling_importance: 9,
    shooting_importance: 8,
    crossing_importance: 5,
    tackling_importance: 3,
    marking_importance: 3,
    positioning_importance: 8,
    vision_importance: 7,
    decision_importance: 8,
    concentration_importance: 6,
    work_rate_importance: 7,
    teamwork_importance: 7,
    leadership_importance: 5,
    ideal_player_traits: JSON.stringify(['Elite dribbling', 'Shooting', 'Pace', 'Cuts inside']),
    preferred_foot: 'opposite to side',
    height_requirement: 'any',
    age_profile: 'peak pace',
    real_world_examples: JSON.stringify(['Mohamed Salah', 'Arjen Robben', 'Bukayo Saka', 'Phil Foden']),
    historical_examples: JSON.stringify(['Robben pioneer', 'Modern mainstream']),
    synergizes_with: JSON.stringify(['Overlapping FB', 'Target man', 'Traditional winger opposite']),
    conflicts_with: JSON.stringify(['Inverted FB same side']),
    complementary_roles: JSON.stringify(['Overlapping FB', 'Traditional winger opposite']),
    requires_support_from: JSON.stringify(['FB overlaps for width']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', '4-3-2-1', 'Any with wingers']),
    tactical_systems_compatibility: JSON.stringify(['Modern attacking', 'Liverpool Salah', 'Bayern Robben']),
    versatility_score: 7,
    difficulty_to_play: 7,
    impact_on_team: 9,
    specific_instructions: 'Cut inside constantly! Shoot! Dribble! Take on defenders!',
    in_possession_role: 'Cut inside. Shoot. Create angles.',
    out_of_possession_role: 'Minimal defending. Press sometimes.',
    transition_role: 'Quick counter-attacks. Pace critical.',
    role_variants: JSON.stringify(['Pure goalscorer', 'More creative', 'Balanced']),
    modern_adaptations: JSON.stringify(['Mainstream now', 'Goals focus increased'])
  },
  {
    role_name: 'Advanced Forward',
    position: 'FW',
    sub_position: 'ST',
    mentality: 'attack',
    description: 'Pure goalscorer stays high. Erling Haaland, Harry Kane, Romelu Lukaku.',
    detailed_explanation: 'Advanced forward pure finisher. Stays highest. Clinical finishing.',
    tactical_purpose: 'Score goals. Stretch defense. Target for passes.',
    movement_pattern: 'Stay high. Runs in behind. Penalty box focus.',
    positioning: 'Highest player. On shoulder of last defender.',
    off_ball_movement: 'Runs in behind. Penalty box movement.',
    on_ball_behavior: 'Clinical finishing. Hold-up when needed.',
    primary_duties: JSON.stringify(['Goals primary', 'Finish chances', 'Runs in behind']),
    secondary_duties: JSON.stringify(['Hold-up play', 'Link occasionally', 'Penalties']),
    defensive_duties: JSON.stringify(['None', 'Minimal pressing']),
    attacking_duties: JSON.stringify(['Goals only focus', 'Clinical finishing', 'Movement']),
    pace_importance: 8,
    stamina_importance: 7,
    strength_importance: 8,
    agility_importance: 7,
    jumping_importance: 8,
    passing_importance: 5,
    dribbling_importance: 6,
    shooting_importance: 10,
    crossing_importance: 3,
    tackling_importance: 2,
    marking_importance: 2,
    positioning_importance: 10,
    vision_importance: 6,
    decision_importance: 8,
    concentration_importance: 9,
    work_rate_importance: 6,
    teamwork_importance: 6,
    leadership_importance: 6,
    ideal_player_traits: JSON.stringify(['Elite finishing', 'Movement', 'Clinical', 'Positioning genius']),
    preferred_foot: 'strong',
    height_requirement: 'tall preferred',
    age_profile: 'peak',
    real_world_examples: JSON.stringify(['Erling Haaland', 'Harry Kane', 'Romelu Lukaku', 'Ciro Immobile']),
    historical_examples: JSON.stringify(['Filippo Inzaghi', 'Ruud van Nistelrooy', 'Thierry Henry']),
    synergizes_with: JSON.stringify(['Creative midfielders', 'Wingers', 'Playmakers']),
    conflicts_with: JSON.stringify(['Another advanced forward', 'False 9']),
    complementary_roles: JSON.stringify(['Roaming playmaker', 'Inverted wingers', 'Creative 10']),
    requires_support_from: JSON.stringify(['Creative players', 'Wingers for crosses']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', '4-3-2-1', 'Any single striker']),
    tactical_systems_compatibility: JSON.stringify(['Man City Haaland', 'Modern goalscoring', 'Universal']),
    versatility_score: 5,
    difficulty_to_play: 6,
    impact_on_team: 10,
    specific_instructions: 'Stay high! Finish chances! Runs in behind! Clinical!',
    in_possession_role: 'Target for passes. Finish chances.',
    out_of_possession_role: 'Stay high. Minimal defending.',
    transition_role: 'Target for counter-attacks. Pace in behind.',
    role_variants: JSON.stringify(['Pure poacher', 'More complete', 'Hold-up focus']),
    modern_adaptations: JSON.stringify(['Still effective', 'Haaland proves value'])
  },
  {
    role_name: 'Ball-Winning Midfielder',
    position: 'MF',
    sub_position: 'DM/CM',
    mentality: 'defend',
    description: 'Aggressive ball winner. N Golo Kante, Gennaro Gattuso, Claude Makelele.',
    detailed_explanation: 'Ball-winning midfielder aggressive tackles and interceptions. Engine.',
    tactical_purpose: 'Win ball back. High intensity. Break up play.',
    movement_pattern: 'Aggressive movements to ball. Cover ground.',
    positioning: 'Active positioning. Hunt the ball.',
    off_ball_movement: 'Constant pressing. Hunt ball carrier.',
    on_ball_behavior: 'Simple passing. Quick release.',
    primary_duties: JSON.stringify(['Win ball', 'Tackles', 'Interceptions', 'Intensity']),
    secondary_duties: JSON.stringify(['Simple passing', 'Cover', 'Energy']),
    defensive_duties: JSON.stringify(['Aggressive tackling', 'Hunt ball', 'High intensity']),
    attacking_duties: JSON.stringify(['Minimal', 'Simple passes', 'Recycle']),
    pace_importance: 8,
    stamina_importance: 10,
    strength_importance: 7,
    agility_importance: 8,
    jumping_importance: 6,
    passing_importance: 6,
    dribbling_importance: 5,
    shooting_importance: 4,
    crossing_importance: 3,
    tackling_importance: 10,
    marking_importance: 8,
    positioning_importance: 8,
    vision_importance: 6,
    decision_importance: 8,
    concentration_importance: 9,
    work_rate_importance: 10,
    teamwork_importance: 9,
    leadership_importance: 7,
    ideal_player_traits: JSON.stringify(['Elite tackling', 'Incredible stamina', 'Aggression', 'Engine']),
    preferred_foot: 'any',
    height_requirement: 'any',
    age_profile: 'peak fitness',
    real_world_examples: JSON.stringify(['N Golo Kante', 'Declan Rice', 'Casemiro prime', 'Wilfred Ndidi']),
    historical_examples: JSON.stringify(['Gennaro Gattuso', 'Claude Makelele', 'Roy Keane']),
    synergizes_with: JSON.stringify(['Playmakers', 'Creative players', 'Advanced players']),
    conflicts_with: JSON.stringify(['Another ball-winner', 'Destroyer']),
    complementary_roles: JSON.stringify(['Roaming playmaker', 'Regista', 'Advanced players']),
    requires_support_from: JSON.stringify(['CB cover']),
    best_in_formations: JSON.stringify(['4-3-3', '4-2-3-1', 'Any midfield']),
    tactical_systems_compatibility: JSON.stringify(['Leicester Kante', 'Modern defensive', 'Universal']),
    versatility_score: 6,
    difficulty_to_play: 7,
    impact_on_team: 9,
    specific_instructions: 'Win ball! Tackle! Never stop! Hunt ball carrier!',
    in_possession_role: 'Simple passing. Quick release.',
    out_of_possession_role: 'Win ball back. Aggressive tackling.',
    transition_role: 'Quick to win ball. Start counter.',
    role_variants: JSON.stringify(['More aggressive', 'More disciplined', 'Box-to-box hybrid']),
    modern_adaptations: JSON.stringify(['Still essential', 'Passing improved'])
  },
  {
    role_name: 'Deep-Lying Forward',
    position: 'FW',
    sub_position: 'ST/CF',
    mentality: 'support',
    description: 'Striker drops deep to link. Harry Kane, Karim Benzema, Zlatan.',
    detailed_explanation: 'Deep-lying forward drops to midfield. Complete striker. Link play genius.',
    tactical_purpose: 'Link play. Drop deep. Create space. Passes and goals.',
    movement_pattern: 'Drop deep frequently. Create space.',
    positioning: 'Striker but drops to midfield often.',
    off_ball_movement: 'Drop deep. Create space for runners.',
    on_ball_behavior: 'Elite passing. Hold-up. Through balls.',
    primary_duties: JSON.stringify(['Link play', 'Drop deep', 'Create', 'Hold-up']),
    secondary_duties: JSON.stringify(['Goals', 'Assists', 'Target']),
    defensive_duties: JSON.stringify(['Minimal', 'Press sometimes']),
    attacking_duties: JSON.stringify(['Link play primary', 'Goals', 'Assists', 'Create']),
    pace_importance: 6,
    stamina_importance: 7,
    strength_importance: 8,
    agility_importance: 6,
    jumping_importance: 7,
    passing_importance: 9,
    dribbling_importance: 7,
    shooting_importance: 8,
    crossing_importance: 5,
    tackling_importance: 3,
    marking_importance: 3,
    positioning_importance: 9,
    vision_importance: 9,
    decision_importance: 9,
    concentration_importance: 7,
    work_rate_importance: 7,
    teamwork_importance: 9,
    leadership_importance: 8,
    ideal_player_traits: JSON.stringify(['Elite passing', 'Intelligence', 'Hold-up', 'Complete']),
    preferred_foot: 'strong',
    height_requirement: 'tall preferred',
    age_profile: 'peak or experience',
    real_world_examples: JSON.stringify(['Harry Kane', 'Karim Benzema', 'Zlatan Ibrahimovic', 'Olivier Giroud']),
    historical_examples: JSON.stringify(['Dennis Bergkamp', 'Teddy Sheringham', 'Francesco Totti']),
    synergizes_with: JSON.stringify(['Inside forwards', 'Shadow striker', 'Runners from midfield']),
    conflicts_with: JSON.stringify(['False 9', 'Another deep forward']),
    complementary_roles: JSON.stringify(['Inside forward', 'Shadow striker', 'Box-to-box']),
    requires_support_from: JSON.stringify(['Runners from wide and midfield']),
    best_in_formations: JSON.stringify(['4-2-3-1', '4-3-3', '4-3-1-2', 'Flexible systems']),
    tactical_systems_compatibility: JSON.stringify(['Tottenham Kane', 'Real Madrid Benzema', 'Modern complete']),
    versatility_score: 8,
    difficulty_to_play: 8,
    impact_on_team: 9,
    specific_instructions: 'Drop deep! Link play! Hold-up! Through balls! Goals too!',
    in_possession_role: 'Link play hub. Create and score.',
    out_of_possession_role: 'Minimal defending. Press intelligently.',
    transition_role: 'Hold-up. Quick link play.',
    role_variants: JSON.stringify(['More creative', 'More goalscoring', 'Balanced complete']),
    modern_adaptations: JSON.stringify(['Essential for lone striker', 'Complete required'])
  }
];

let completed = 0;
const stmt = db.prepare(`INSERT OR IGNORE INTO player_roles (
  role_name, position, sub_position, mentality, description, detailed_explanation,
  tactical_purpose, movement_pattern, positioning, off_ball_movement, on_ball_behavior,
  primary_duties, secondary_duties, defensive_duties, attacking_duties,
  pace_importance, stamina_importance, strength_importance, agility_importance, jumping_importance,
  passing_importance, dribbling_importance, shooting_importance, crossing_importance,
  tackling_importance, marking_importance, positioning_importance,
  vision_importance, decision_importance, concentration_importance,
  work_rate_importance, teamwork_importance, leadership_importance,
  ideal_player_traits, preferred_foot, height_requirement, age_profile,
  real_world_examples, historical_examples,
  synergizes_with, conflicts_with, complementary_roles, requires_support_from,
  best_in_formations, tactical_systems_compatibility,
  versatility_score, difficulty_to_play, impact_on_team,
  specific_instructions, in_possession_role, out_of_possession_role, transition_role,
  role_variants, modern_adaptations
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);

roles.forEach((r, i) => {
  stmt.run(
    r.role_name, r.position, r.sub_position, r.mentality, r.description, r.detailed_explanation,
    r.tactical_purpose, r.movement_pattern, r.positioning, r.off_ball_movement, r.on_ball_behavior,
    r.primary_duties, r.secondary_duties, r.defensive_duties, r.attacking_duties,
    r.pace_importance, r.stamina_importance, r.strength_importance, r.agility_importance, r.jumping_importance,
    r.passing_importance, r.dribbling_importance, r.shooting_importance, r.crossing_importance,
    r.tackling_importance, r.marking_importance, r.positioning_importance,
    r.vision_importance, r.decision_importance, r.concentration_importance,
    r.work_rate_importance, r.teamwork_importance, r.leadership_importance,
    r.ideal_player_traits, r.preferred_foot, r.height_requirement, r.age_profile,
    r.real_world_examples, r.historical_examples,
    r.synergizes_with, r.conflicts_with, r.complementary_roles, r.requires_support_from,
    r.best_in_formations, r.tactical_systems_compatibility,
    r.versatility_score, r.difficulty_to_play, r.impact_on_team,
    r.specific_instructions, r.in_possession_role, r.out_of_possession_role, r.transition_role,
    r.role_variants, r.modern_adaptations,
    (err) => {
      if (err) {
        console.log(`❌ ${r.role_name} - Hata: ${err.message}`);
      } else {
        completed++;
        console.log(`✅ ${completed}/7: ${r.role_name} eklendi!`);
      }
    }
  );
});

stmt.finalize(() => {
  console.log(`\n🎯 ${completed}/7 ek rol başarıyla eklendi!`);
  console.log(`\n📊 Toplam roller şimdi 17 + 5 + 7 = 29 olmalı!`);
  db.close();
});
