const ultraDb = require('./ultra_database');

console.log('🔥 TACTICAL SYSTEMS ZENGİNLEŞTİRME BAŞLIYOR...\n');

const updates = [
  // 4-2-3-1 Guardiola
  {
    id: 1,
    system_type: 'Top Hakimiyeti',
    attacking_phase: `Guardiola'nın 4-2-3-1 sisteminde hücum fazı son derece organize ve karmaşıktır. İki pivot (çift 6'lar), sürekli olarak savunma hattından pas alma seçenekleri sunar. Tam beklerde (fullback'ler) sahaya kanat açısı verirken, iç kanatlar (inverted wingers) dar pozisyon alarak merkezi doldurmaya ve yarı alanlardan (half-space) oynamaya odaklanır. 10 numara (CAM), rakip savunma hattı arasında sürekli hareket ederek pas alma noktaları yaratır. Forvet, genellikle false 9 rolüyle geri çekilip oyun kurmaya katılır veya klasik hedef adam olarak kalıpların bozulmasını sağlar. Takım, rakip pressinginden kısa paslarla çıkmak için sürekli üçgenler oluşturur. Pozisyonel rotasyonlar (pozisyonel değişimler) ve overload (aşırı yükleme) prensipleri, rakip savunmayı desoriente etmek için kullanılır.`,
    defensive_phase: `Savunma fazında, takım genellikle yüksek bir blok oluşturur ve topun rakipte olduğu andan itibaren baskı yapar. Ancak Guardiola'nın sistemi sadece presingle sınırlı değildir - takım, eğer press kırılırsa hızlıca kompakt bir orta bloka geçiş yapar. İki pivot (çift 6'lar) merkezi boşluğu kapatır, tam bekler dar pozisyon alarak iç geçişlere karşı koruma sağlar. Kanatlar, rakip beklerine karşı sorumludur ve içeriye kesilen pasları engellemeye çalışır. 10 numara ve forvet, rakip savunma hattının build-up yapmasını engellemek için sürekli pozisyon alır. Eğer rakip kanat üzerinden oynarsa, kanat oyuncusu ve tam bek çift press yapar. Takım, topun etrafında kompaktlık oluşturarak rakibin pas seçeneklerini kısıtlar ve top kazanımı anında kontra atak için hazırdır.`,
    transition_attack: `Guardiola'nın geçiş hücumu (transition attack), planlanmış pozisyonel saldırılardan daha farklıdır ancak yine de kontrollüdür. Top kazanımı sonrası, takım anında ileri paslar aramaz - bunun yerine topu korur ve pozisyonel üstünlük kazanmaya çalışır. Eğer ön bölgede büyük bir boşluk varsa, hızlı oyuncular (özellikle kanatlar ve CAM) dikey koşular yapar. Pivotlar hızlıca topu ileri taşır veya uzun pas seçenekleri arar. Tam bekler, hızla kanatlara destek sağlamak için öne çıkar. Anahtar, "kontrollü kontra" - topu koruyarak ilerlemek ve rakip savunma organizasyonunu kurmadan pozisyon bulmak. Takım asla topa sahipliği kaybetme riskine girmez; eğer hızlı hücum mümkün değilse, possession'a geri döner ve sabırla rakip savunmayı yıpratır.`,
    transition_defense: `Savunma geçişi (transition defense), Guardiola sisteminde kritik bir unsurdur çünkü takım sürekli yüksek pozisyon alır. Top kaybı anında, tüm oyuncular anında "counter-press" (karşı press) başlatır - topun etrafında 5-6 saniye içinde yoğun bir baskı oluşturur. Amaç, topu hemen geri almak veya rakibin kontra atağını başlamadan durdurmaktır. Eğer counter-press başarısız olursa, takım hızla geriye koşar ve kompakt bir savunma şekli oluşturur. Pivotlar, merkezi boşluğu kapatmak için geriye çekilir. Tam bekler, dar pozisyon alarak kanat geçişlerini engeller. Kanat oyuncuları, rakip beklere karşı geri takip yapar. Takım, orta alanda sayısal üstünlük sağlayarak rakibin forward pass (ileri pas) yapmasını zorlaştırır. Eğer rakip hızlı kontra atağa çıkarsa, son çare olarak taktiksel faul kullanılabilir (oyunu durdurup reorganizasyon için zaman kazanma).`
  },

  // 4-3-3 Klopp Gegenpressing
  {
    id: 2,
    system_type: 'Yüksek Yoğunluk',
    attacking_phase: `Klopp'un 4-3-3 gegenpressing sisteminde hücum fazı son derece dikey ve hızlıdır. Sistem, geniş kanat oyuncularının (wingers) sürekli derinliğe koşması üzerine kuruludur. Forvet (false 9 veya target man), savunma hattını meşgul ederken, kanatlar yan koridorlardan içeriye kesilen koşularla gol fırsatları arar. Orta saha üçlüsü, dengeli bir şekilde hücuma ve savunmaya katkı sağlar: 6 numara (holding midfielder) merkezi korurken, iki 8 numara (box-to-box midfielders) ileri dalışlar yapar, ceza sahası içine girişler sağlar ve ikinci topları kazanır. Tam bekler, kanat oyuncularının içeriye kesilmesiyle oluşan boşlukları doldurarak yan koridorlardan yükselir ve cross (orta) yapma seçenekleri sunar. Hücum, hızlı pas kombinasyonlarından, wing play'den (kanat oyunu) ve direct running (direk koşu) ile karakterize edilir. Takım, sürekli tempo ve yoğunlukla rakip savunmayı bunaltmayı hedefler.`,
    defensive_phase: `Klopp'un sistemi, "Heavy Metal Football" olarak bilinir - agresif, yüksek yoğunluklu ve sürekli baskı yapan bir tarz. Savunma fazında, takım çok yüksek bir defensive line (savunma hattı) kullanır, genellikle orta saha çizgisi civarında veya daha ileride. Amaç, rakibi kendi yarı sahasına hapsetmek ve top kazanımını rakip kaleye yakın bölgelerde yapmaktır. Kanat oyuncuları, rakip beklerine agresif baskı yapar ve backward pass'leri (geri paslar) engellemeye çalışır. Forvet, rakip stoperlere press yapar ve savunma ortasından build-up yapılmasını zorlaştırır. Orta saha üçlüsü, merkez alanı kapatır ve rakibin orta sahadan geçişini engeller. Tam bekler, geniş pozisyon alır ancak rakip kanatlarına karşı 1v1 mücadelelere hazır olmalıdır. Eğer press kırılırsa, takım hızla compact block (kompakt blok) oluşturur ve orta alanda sayısal üstünlük sağlar. Offside trap (ofsayt tuzağı) sık kullanılır.`,
    transition_attack: `Gegenpressing sisteminin DNA'sı, geçiş hücumudur (transition attack). Klopp'un "win the ball back within 6 seconds" (6 saniye içinde topu geri kazan) mottosu burada devreye girer. Top kazanımı anında, takım milisaniyeler içinde hızlı dikey paslar arar. Kanat oyuncuları, savunma hatlarının arkasına koşular yapar. Orta saha 8'leri, boşluklara dalış yapar. Forvet, topu tutmak yerine hızlı wall pass (duvar pası) seçenekleri sunar veya arkaya koşuları başlatır. Anahtar, "hızlı karar verme" ve "risk alma"dır - takım, rakip savunma organize olmadan pozisyona girmeyi hedefler. Tam bekler, hızla kanat koridorlarına overlap (bindirme) yapar. Eğer rakip sayıca az ise (numerical disadvantage), takım mercilessly (acımasızca) overload oluşturur ve 3v2, 4v3 gibi üstünlükler yaratır. Counterattack çok hızlıdır - 3-5 pas içinde gol fırsatı yaratma hedefi vardır.`,
    transition_defense: `Geçiş savunması (transition defense), Klopp'un sisteminde "counter-press" (gegenpressing) kavramıyla eş anlamlıdır. Top kaybı anında, topun etrafındaki 5-6 oyuncu anında yoğun baskı oluşturur. Amaç: topu 5-8 saniye içinde geri almak. Bu, sadece top kazanma değil, aynı zamanda rakibin kontra atağını başlamadan durdurma stratejisidir. Eğer counter-press başarısız olursa, takım disiplinli bir şekilde geriye koşar - ancak bu nadir bir durumdur çünkü sistem üst düzey fitness gerektirir. Orta saha 6'sı, merkezi kapatmak için crucial (kritik) role sahiptir. Tam bekler, hızla dar pozisyona gelir ve kanat geçişlerini engeller. Stoperler, yüksek line'dan (hat) geriye çekilmeden önce offside trap kullanır. Takım, orta alanda compactness (kompaktlık) sağlar ve rakibin through ball (ara pas) yapmasını zorlaştırır. Kaleci, süpürücü (sweeper-keeper) olarak yüksek pozisyon alır ve arka boşlukları temizler.`
  },

  // 3-5-2 Conte Wing-Back System
  {
    id: 3,
    system_type: 'Hibrit (Savunma/Hücum)',
    attacking_phase: `Conte'nin 3-5-2 sisteminde hücum fazı, kanat beklerinin (wing-backs) oyun kurma ve sonlandırma yeteneğine büyük oranda dayanır. Üç stoper, savunmada güvenli bir temel oluştururken, iki kanat beki tüm yan koridorları kaplar - hem savunma hem hücumda. Hücum fazında, kanat bekleri neredeyse kanatçı (winger) gibi davranır, rakip ceza sahasına kadar çıkar ve cross (orta) yapma, cut-back (geri çekme) ve hatta gol atma seçenekleri sunar. Merkez orta saha üçlüsü, genellikle bir Regista (derin oyun kurucu), bir Mezzala (box-to-box) ve bir şartlı 10 numaradan oluşur. İki forvet, birbirini tamamlayıcı roller oynar: biri target man (hedef adam) olarak tutma ve lay-off (kısa pas) yaparken, diğeri behind defanse (savunma arkasına) koşular yapar. Takım, merkez ve kanatlar arasında sürekli rotasyon ve overload yaratır. 3-5-2, 3-4-3 veya 5-2-3'e değişebilir, game phase'e (oyun fazına) göre.`,
    defensive_phase: `Savunma fazında, 3-5-2 sistemi genellikle 5-3-2 veya 5-4-1 şekline dönüşür. Kanat bekleri (wing-backs) geri çekilir ve lateraller (side center-backs) ile birlikte beş kişilik bir savunma hattı oluşturur. Bu, son derece solid (sağlam) ve organize bir blok yaratır. Merkez üçlüsü, orta sahanın merkezini kapatır ve rakibin through pass (ara pas) yapmasını zorlaştırır. İki forvet, rakip build-up'a minimal baskı yapar ancak geriye koşu yapmazlar - enerjiyi hücum için saklamaya odaklanırlar. Takım, genellikle mid-block (orta blok) veya low-block (düşük blok) stratejisi kullanır, compact kalır ve rakibi wing play (kanat oyunu) veya long-range shots (uzak mesafe şut) gibi düşük verimli seçeneklere zorlar. Üç stoper sistemi, aerial dominance (hava hakimiyeti) sağlar ve set-piece (duran top) savunmasında güçlüdür. Eğer bir kanat bek hücumda kalırsa, lateraller onun boşluğunu kapatır (cover) - bu, takımın asimetrik şekillerde rahat oynamasını sağlar.`,
    transition_attack: `3-5-2'de geçiş hücumu (transition attack) genellikle kanat beklerinin hızlı forward runs (ileri koşular) ile başlar. Top kazanımı sonrası, kanat bekleri anında boş koridorlara sprint yapar. Eğer rakip beşli savunma oyunuyorsa, numerical advantage (sayısal üstünlük) yoktur, bu yüzden central overload (merkez aşırı yüklemesi) kullanılır. Orta saha üçlüsü, hızla topu ileri taşır - Regista, long pass (uzun pas) seçenekleri ararken, Mezzala diagonal runs (çapraz koşular) yapar. İki forvet, one-two (bir-iki) kombinasyonları ve quick flick-ons (hızlı dokunuşlar) kullanarak tempo yaratır. Takım, wing-backs'in overlapping runs (bindirme koşuları) sayesinde 2v1 situations (2'ye 1 durumlar) yaratmayı sever. Eğer kanat bekleri henüz ileri pozisyonda değilse, takım topu koruyarak bekler ve pozisyonel superiority (pozisyonel üstünlük) kazanır. Counterattack, direct (direk) değil, controlled (kontrollü) ve structured (yapılandırılmış) bir şekilde gerçekleştirilir.`,
    transition_defense: `Geçiş savunmasında (transition defense), 3-5-2 sisteminin asıl gücü ortaya çıkar: beş kişilik savunma hattına hızlı dönüş. Kanat bekleri, top kaybı anında immediately sprint back (hemen geri koşar) - bu, Conte'nin sisteminin en critical (kritik) unsurudur ve extraordinary fitness (olağanüstü kondisyon) gerektirir. Eğer bir kanat bek henüz geri dönmediyse, lateral stoper onun boşluğunu kapatır (slide across). Merkez üçlüsü, central zones (merkez bölgeleri) kapatır ve counterattack'in through middle (ortadan) gelmesini engeller. İki forvet, geri takip yapmaz ancak passing lanes (pas yollarını) kapatır ve rakibi wing areas'a (kanat bölgelerine) zorlar. Takım, orta sahada compact kalarak rakibin progressive passes (ilerletici paslar) yapmasını zorlaştırır. Eğer bir through ball gelirse, sweeper (süpürücü/libero pozisyonundaki) merkez stoper devreye girer. Takım, defensive solidity (savunma sağlamlığı) sayesinde counterattack risk minimize eder ve rakibi wide areas'ta (geniş alanlarda) isolate eder.`
  },

  // 4-4-2 Classic
  {
    id: 4,
    system_type: 'Dengeli Sistem',
    attacking_phase: `Klasik 4-4-2, futbol tarihinin en iconic (ikonik) ve balanced (dengeli) formasyonlarından biridir. Hücum fazında, takım genellikle wing play (kanat oyunu) üzerine kurulur. İki kanat oyuncusu (wingers), touchline'a yakın (yan çizgiye yakın) geniş pozisyon alır ve rakip beklerini 1v1 durumlarında zorlar. Amaç, ceza sahasına cross (orta) yapmak ve iki forvetin aerial strength (hava gücü) ve positioning (pozisyon alma) yeteneğinden yararlanmaktır. Merkez orta saha ikilisi, genellikle bir destroyer (yıkıcı/holding) ve bir box-to-box oyuncudan oluşur. Holding midfielder savunmayı korurken, box-to-box hücuma destek verir ve late runs (geç dalışlar) ile ceza sahasına girer. İki forvet, partner striker relationship (ortak forvet ilişkisi) çok önemlidir: biri target man (hedef adam) olarak tutma ve flick-on (dokunuş) yaparken, diğeri poacher (fırsatçı) rolüyle gol fırsatlarını değerlendirir. Tam bekler, overlapping runs (bindirme koşuları) yaparak kanat oyuncularına destek sağlar. Sistem, direct (direk) ve straightforward (açık), karmaşık rotasyonlardan ziyade clear roles (net roller) ve partnerships (ortaklıklara) dayanır.`,
    defensive_phase: `Savunma fazında, 4-4-2 son derece compact (kompakt) ve organized (organize) bir blok oluşturur. Takım, genellikle two banks of four (iki dörtlü hat) oluşturur: bir savunma dörtlüsü ve bir orta saha dörtlüsü. Bu, pitch'i (sahayı) iyi bir şekilde kaplar ve rakibin through middle (ortadan geçmesini) zorlaştırır. İki forvet, rakip savunmaya minimal press yapar ancak passing lanes (pas yollarını) kapatır ve backward passes (geri pasları) zorlar. Orta saha hattı, narrow (dar) veya wide (geniş) kalarak game situation'a (oyun durumuna) göre adjust eder (uyarlanır). Eğer rakip kanat oyunuyla gelirse, kanat oyuncusu ve tam bek double-team (çift takım) oluşturur. Holding midfielder, central zones (merkez bölgeleri) kapatır ve stoperlerin önünde shield (kalkan) görevi görür. Takım, mid-block (orta blok) veya low-block (düşük blok) kullanarak rakibi wing play'e (kanat oyununa) veya long shots'a (uzak şutlara) zorlar. Offside trap nadiren kullanılır - sistem, deep defensive line (derin savunma hattı) ile safety first (güvenlik öncelikli) yaklaşımı benimser. Set-piece defense (duran top savunması) güçlüdür çünkü sistem height (boy) ve physicality (fiziksel güç) avantajlarından yararlanır.`,
    transition_attack: `4-4-2'de counterattack (kontra atak), sisteminki en lethal (öldürücü) silahlarından biridir. Top kazanımı sonrası, takım hızla long ball (uzun top) veya through ball (ara pas) ile iki forveti hedefler. Kanat oyuncuları, anında wide areas'a (geniş alanlara) sprint yapar ve opposition fullbacks'i (rakip beklerini) isolate eder. Box-to-box midfielder, late runs (geç dalışlar) ile counter'a katılır ve numerical advantage (sayısal üstünlük) yaratır. İki forvet arasındaki understanding (anlayış) kritiktir: target man hold-up play (tutma oyunu) yaparken, striker behind (arkasındaki forvet) deep runs (derin koşular) yapar. Tam bekler, genellikle counterattack'e katılmaz - defensive stability (savunma istikrarı) için back position (arka pozisyonda) kalırlar. Transition, direct (direk) ve fast (hızlı) - minimal touches (minimum dokunuş) ve quick passes (hızlı paslar). Eğer counterattack slow down (yavaşlarsa), takım possession'a (topa sahipliğe) geçer ve wide play (geniş oyun) ile rakip savunmayı stretch eder (gerir).`,
    transition_defense: `Geçiş savunması (transition defense), 4-4-2'de immediate organization (anında organizasyon) gerektirir. Top kaybı sonrası, takım hızla two banks of four (iki dörtlü hat) şekline döner. Kanat oyuncuları, geri koşarak tam beklere destek sağlar ve wing areas'ı (kanat bölgelerini) kapatır. Box-to-box midfielder, merkeze döner ve holding midfielder ile ortaklık kurarak central areas (merkez alanları) korur. İki forvet, agresif bir şekilde geri pressing yapmaz - bunun yerine passing lanes (pas yollarını) block eder (bloke eder) ve rakibi sideways passes'e (yan paslar) zorlar. Tam bekler, narrow position (dar pozisyon) alarak inside cuts (içeriye kesme) engellerken, stoperler goal-side (kale tarafında) kalır ve through balls'a (ara paslar) karşı hazırlıklıdır. Takım, quickly regain shape (hızla şekil kazanma) yeteneğine dayanır - 4-4-2'nin beauty (güzelliği), simplicity (basitliği) ve clarity (netliktir). Eğer rakip fast break'e (hızlı atağa) çıkarsa, takım tactical foul (taktiksel faul) kullanarak play'i durdurabilir (oyunu durdurur) ve regroup time (yeniden toplanma zamanı) kazanır.`
  },

  // 3-4-3 Attacking
  {
    id: 5,
    system_type: 'Top Hakimiyeti',
    attacking_phase: `3-4-3 formasyonu, modern futbolun en attack-minded (hücum odaklı) sistemlerinden biridir. Hücum fazında, üç forvet numerical advantage (sayısal üstünlük) yaratır: bir merkez forvet ve iki kanat forveti. Kanat forvetleri, touchline'a yakın wide positions (geniş pozisyonlar) alarak pitch'i stretch eder (sahayı gerir) ve opposition defense'i (rakip savunmayı) thin spread out (ince bir şekilde yayılmaya) zorlar. Merkez forvet, hold-up play (tutma oyunu), link-up (bağlantı kurma) ve goalscoring (gol atma) yapabilmeli - multi-dimensional striker (çok yönlü forvet) gerekir. İki central midfielder (orta saha), box-to-box roles (box-to-box roller) oynar ve hem savunmada hem hücumda denge sağlar. Üç stoper sistemi, bir oyuncunun (genellikle merkez stopper/libero) topu forward'a taşımasına (ileri taşıma) izin verir, build-up phase'de (oyun kurma fazında) numerical superiority (sayısal üstünlük) yaratır. Wing-backs, kritik rollerdir - hem defensive cover (savunma desteği) hem attacking width (hücum genişliği) sağlamalıdırlar. Sistem, overload (aşırı yükleme), rotation (rotasyon) ve positional interchange (pozisyonel değişim) ile dominant possession (baskın topa sahip olma) yaratmayı hedefler.`,
    defensive_phase: `Savunma fazında, 3-4-3 genellikle 5-4-1 veya 5-2-3 şekline dönüşür. Wing-backs geri çekilir ve üç stoperle birlikte beşli savunma hattı oluşturur. Bu, pitch width'i (saha genişliğini) cover eder (kaplar) ve wing play'e (kanat oyununa) karşı güçlü bir shield (kalkan) sağlar. İki central midfielder, orta sahada compact kalır ve through middle (ortadan geçişi) engeller. Üç forvet, high press (yüksek press) uygulayabilir veya drop deep (derine düşebilir), tactical approach'a (taktiksel yaklaşıma) bağlı olarak. Eğer takım high press kullanırsa, wing forwards (kanat forvetleri) opposition fullbacks'i (rakip beklerini) engage eder (meşgul eder), center forward ise central defenders'ı (merkez stoperleri) press eder. Üç stoper sistemi, aerial dominance (hava hakimiyeti) ve physicality (fiziksel güç) advantage'i (avantajı) sağlar. Wing-backs'in defensive work-rate (savunma iş oranı), sistem success'ünün (başarı) key'idir (anahtarıdır) - eğer wing-back geri dönmede slow (yavaş) olursa, side (yan taraf) exposed (açığa çıkar) kalır. Takım, mid-block veya low-block kullanarak compact kalır ve counterattacking opportunities (kontra atak fırsatları) arar.`,
    transition_attack: `3-4-3'te transition attack (geçiş hücumu), extreme pace (aşırı hız) ve width (genişlik) ile karakterize edilir. Top kazanımı sonrası, üç forvet anında forward runs (ileri koşular) yapar. Kanat forvetleri, opposition fullbacks behind (rakip beklerin arkasına) sprint eder, merkez forvet ise space between defenders (savunucular arası boşluğu) exploit eder (istismar eder). Wing-backs, overlapping runs (bindirme koşuları) ile extra attacking options (ekstra hücum seçenekleri) sağlar. İki central midfielder, quick vertical passes (hızlı dikey paslar) ve through balls (ara paslar) ile transition'ı orchestrate eder (yönetir). Üç stopper sisteminin bir advantage'i (avantajı), one defender can step forward (bir savunucunun ileri çıkabilmesi) with ball carry (topla taşıma), counter'ı başlatma yeteneğidir. Sistem, 3v2 veya 4v3 overloads (aşırı yüklemeler) yaratmayı sever - wing forwards (kanat forvetleri) wide stretch (geniş gerilme) yaparken, central areas (merkez alanlar) flooding (sele yapar). Transition, direct (direk) veya patient (sabırlı) olabilir, opposition setup'a (rakip düzenine) göre adjust eder (uyarlanır).`,
    transition_defense: `Transition defense (geçiş savunması), 3-4-3'te critical (kritik) ve challenging'dir (zorludur) çünkü sistem inherently attack-minded (doğal olarak hücum odaklıdır). Top kaybı sonrası, immediate counter-press (anında karşı press) başlar - üç forvet ve iki central midfielder ball'ı (topu) surround eder (kuşatır) ve quick recovery (hızlı geri kazanım) için pressing trigger (baskı tetikleyicisi) uygular. Eğer counter-press fail eder (başarısız olursa), wing-backs sprint back (geri koşar) ve five-man defensive line (beş kişilik savunma hattı) oluşturur. Central midfielders, shield (kalkan) role (rol) oynayarak stoperlerin önünde protection (koruma) sağlar. Üç forvet, geri düşmez - bunun yerine passing lanes block eder (pas yollarını bloke eder) ve back passes force eder (geri pasları zorlar). Takım, quickly transition from attack to defense mode (hızla hücumdan savunma moduna geçer), organization için crucial (kritik) seconds (saniyeler) kazanır. Eğer wing-back caught upfield (ileride yakalanırsa), side center-back slide across eder (yan stoper kayar) ve cover space (boşluğu kaplar). Sistem, ultimate defensive discipline (nihai savunma disiplini) ve fitness (kondisyon) gerektirir çünkü wing-backs end-to-end (uçtan uca) koşar.`
  }
];

console.log(`📝 ${updates.length} sistem güncellenecek...\n`);

let completed = 0;

updates.forEach(update => {
  const { id, system_type, attacking_phase, defensive_phase, transition_attack, transition_defense } = update;

  const sql = `UPDATE tactical_systems
               SET system_type = ?,
                   attacking_phase = ?,
                   defensive_phase = ?,
                   transition_attack = ?,
                   transition_defense = ?
               WHERE id = ?`;

  ultraDb.run(sql, [system_type, attacking_phase, defensive_phase, transition_attack, transition_defense, id], function(err) {
    if (err) {
      console.error(`❌ Sistem ID ${id} güncellenemedi:`, err.message);
    } else {
      completed++;
      console.log(`✅ Sistem ID ${id} güncellendi (${completed}/${updates.length})`);
    }

    if (completed === updates.length) {
      console.log('\n🎉 İLK 5 SİSTEM TAMAMLANDI!\n');
      ultraDb.close();
    }
  });
});
