const db = require('./ultra_database');

console.log('\n🔄 KALAN TACTICAL CONCEPTS TÜRKÇE ÇEVİRİ (9-31)...\n');

const turkishConcepts = [
  { id: 9, concept_name: 'Rondolar (Pas Çemberleri)', category: 'Antrenman/Felsefe', description: 'Dar alanda hızlı pas alışverişi antrenmanı. Teknik gelişim ve takım uyumu sağlar.', detailed_explanation: 'Küçük alan içinde pas çemberleri. Merkezdeki savunmacı(lar) topu kesmeye çalışır. Barcelona DNA\'sının temeli. Teknik gelişim, hızlı karar verme, takım uyumu. Guardiola ve Cruyff\'un vazgeçilmez antrenman metodu.', principles: JSON.stringify(['Dar alanda pas', 'Hızlı karar verme', 'İyi ilk dokunuş', 'Takım uyumu', 'Sürekli tekrar']), how_to_implement: 'Küçük kare veya daire içinde 8v2, 7v3 gibi formatlar. Merkezdeki savunmalar topu kesmeye çalışır. Sürekli rotasyon. Her antrenmanda 15-20 dakika rondo.', required_player_attributes: JSON.stringify(['Teknik yetenek', 'Hızlı düşünme', 'İyi ilk dokunuş', 'Konsantrasyon', 'Takım çalışması']), suitable_formations: JSON.stringify(['Tüm sistemler için antrenman']), real_world_examples: JSON.stringify(['Barcelona her antrenmanda rondo', 'Man City Guardiola rondo uzmanı', 'Arsenal ısınmalarda rondo']), famous_implementations: JSON.stringify(['Cruyff Barcelona', 'Guardiola tüm takımlar']), related_concepts: JSON.stringify(['Tiki-taka', 'Pozisyonel oyun', 'Top hakimiyeti']), opposing_concepts: JSON.stringify(['Fiziksel antrenman', 'Uzun top oyunu']) },

  { id: 10, concept_name: 'Kontr Atak', category: 'Geçiş', description: 'Top kazanımı sonrası hızlı ve direkt ilerleyerek rakip organize olamadan gol arayışı.', detailed_explanation: 'Savunmadan hücuma hızlı geçiş. Rakip dengede değilken hızla ilerlemek. Az sayıda pas, çok hız. Mourinho takımlarının klasiği. Leicester 2016 şampiyonluğunun temeli.', principles: JSON.stringify(['Hızlı geçiş', 'Az pas', 'Direkt ilerleme', 'Rakip dengesizken', 'Gol odaklı']), how_to_implement: 'Top kazanımında hızlı forvetlere direkt top. Kanatlardan hız. Hızlı oyunculara ihtiyaç. Savunmadan atağa 3-4 pas. Rakip organize olamadan bitirme.', required_player_attributes: JSON.stringify(['Hız', 'Pas yeteneği', 'Bitiricilik', 'Karar verme', 'Sprint gücü']), suitable_formations: JSON.stringify(['4-4-2', '4-3-3', '5-3-2']), real_world_examples: JSON.stringify(['Mourinho Real Madrid kontraları', 'Leicester 2015-16 şampiyonluk', 'Atalanta Gasperini kontra uzmanı']), famous_implementations: JSON.stringify(['Mourinho Real Madrid', 'Leicester Ranieri']), related_concepts: JSON.stringify(['Geçiş anları', 'Hızlı oyun', 'Direkt futbol']), opposing_concepts: JSON.stringify(['Top hakimiyeti', 'Pozisyonel oyun']) },

  { id: 11, concept_name: 'Üçgenler ve Eşkenarlar', category: 'Şekil', description: 'Oyuncuların üçgen oluşturarak pas seçenekleri yaratması. Geometrik futbol prensibi.', detailed_explanation: 'Her topa sahip oyuncunun etrafında üçgen şekli. Her zaman 2 pas seçeneği. Geometrik futbolun temeli. Ajax ve Barcelona DNA\'sı. Cruyff\'un temel öğretisi.', principles: JSON.stringify(['Üçgen formasyonlar', 'Her zaman 2 pas seçeneği', 'Açılar yarat', 'Geometrik düşünme', 'Sürekli hareket']), how_to_implement: 'Oyunculara üçgen düşünmeyi öğret. Topa yakın 2 oyuncu üçgen oluştursun. Sürekli pozisyon değiştir. Ajax modeli. Koordinasyon antrenmanları.', required_player_attributes: JSON.stringify(['Pozisyon bilinci', 'Teknik yetenek', 'Hareket', 'Taktik anlayış', 'Pas yeteneği']), suitable_formations: JSON.stringify(['4-3-3', 'Eşkenar üçgen sistemleri']), real_world_examples: JSON.stringify(['Ajax altın nesil', 'Barcelona Cruyff/Guardiola', 'Arsenal Arteta 2024']), famous_implementations: JSON.stringify(['Cruyff Ajax ve Barcelona', 'Guardiola sistemleri']), related_concepts: JSON.stringify(['Pozisyonel oyun', 'Rondolar', 'Pas ağları']), opposing_concepts: JSON.stringify(['Doğrusal şekiller', 'Statik pozisyonlar']) },

  { id: 12, concept_name: 'Alçak Blok Savunma', category: 'Savunma', description: 'Takımın kendi kalesine yakın, kompakt savunma yapması. Rakibe alan verir ama kaleye yaklaşmayı zorlaştırır.', detailed_explanation: 'Savunma hattı kendi ceza sahası civarında. 4-5-1 veya 5-4-1 kompakt blok. Rakibe top ve alan ver ama kale önü kapalı. Simeone ve Mourinho takımlarının klasiği.', principles: JSON.stringify(['Düşük savunma hattı', 'Kompakt blok', 'Kale önü kapalı', 'Az boşluk', 'Organize savunma']), how_to_implement: 'Savunma hattını kendi ceza sahasına yakın tut. İki sıra (4-5 veya 5-4) oluştur. Orta alanı kapat. Rakip kanatları kullanmak zorunda kalsın. Direkt toplardan gol arama.', required_player_attributes: JSON.stringify(['Disiplin', 'Kondisyon', 'Konsantrasyon', 'Takım çalışması', 'Dayanıklılık']), suitable_formations: JSON.stringify(['4-5-1', '5-4-1', '4-4-2 düşük']), real_world_examples: JSON.stringify(['Simeone Atletico Madrid', 'Mourinho Chelsea 2004-2015', 'Burnley Sean Dyche']), famous_implementations: JSON.stringify(['Simeone Atletico', 'Mourinho takımları', 'İtalyan takımları klasik']), related_concepts: JSON.stringify(['Kompaktlık', 'Organize savunma', 'Kontra atak']), opposing_concepts: JSON.stringify(['Yüksek savunma hattı', 'Pressing'  ]) },

  { id: 13, concept_name: 'Ofsayt Tuzağı', category: 'Savunma', description: 'Savunma hattının ani çıkışıyla hücum oyuncularını ofsayt konumunda yakalamak.', detailed_explanation: 'Defans hattı koordineli ve ani çıkış yapar. Rakip forvetler ofsayt konumuna düşer. Zamanlama kritik. Postecoglou Tottenham 2024\'te çok kullanıyor. Riskli ama etkili.', principles: JSON.stringify(['Koordineli çıkış', 'Ani hareket', 'Zamanlama', 'Yüksek hat', 'Takım disiplini']), how_to_implement: 'Defans oyuncuları koordineli çıkış antrenmanı. Pas anında veya öncesinde çıkış. Yan hakeme güven. Riskli ama rakibi frustrasyona sokar. Yüksek hat gerekli.', required_player_attributes: JSON.stringify(['Hız', 'Koordinasyon', 'Disiplin', 'Zamanlama', 'Takım çalışması']), suitable_formations: JSON.stringify(['3-4-3', '4-3-3 yüksek hat', 'Modern sistemler']), real_world_examples: JSON.stringify(['Postecoglou Tottenham 2024', 'Arsenal yüksek hat', 'Milan Sacchi dönemi klasik']), famous_implementations: JSON.stringify(['Sacchi Milan', 'Postecoglou Spurs']), related_concepts: JSON.stringify(['Yüksek savunma hattı', 'Kompaktlık', 'Pressing']), opposing_concepts: JSON.stringify(['Düşük blok', 'Derin savunma']) },

  { id: 14, concept_name: 'Hücumda Genişlik', category: 'Hücum', description: 'Saha genişliğini kullanarak rakip savunmayı yayma ve boşluk yaratma.', detailed_explanation: 'Kanatçılar yan çizgiye yakın durur. Rakip savunma genişlemek zorunda kalır. Merkeze boşluk açılır. Ardından içe kesme veya orta. Klasik kanat oyununun modern versiyonu.', principles: JSON.stringify(['Sahayı geniş kullan', 'Kanatlardan oyun', 'Savunmayı yay', 'Merkeze boşluk aç', 'Orta ve kesme']), how_to_implement: 'Kanatçıları geniş tut. Tam bekleri ilerlet. Full genişlik kullan. Rakip kanat bekleri geriye çek. Ardından içeri kes veya orta. Switch oyunları kullan.', required_player_attributes: JSON.stringify(['Hız', 'Dribling', 'Orta yeteneği', 'Dayanıklılık', '1v1']), suitable_formations: JSON.stringify(['4-3-3', '4-2-3-1', '3-5-2']), real_world_examples: JSON.stringify(['Manchester United kanatları', 'Bayern Munich klasik', 'Liverpool Salah-Mane genişlik']), famous_implementations: JSON.stringify(['Ferguson Man Utd', 'Heynckes Bayern']), related_concepts: JSON.stringify(['Kanat oyunu', 'Ortalama', 'İzolasyonlar']), opposing_concepts: JSON.stringify(['Dar hücum', 'Merkez ağırlıklı']) },

  { id: 15, concept_name: 'Dar Eşkenar Orta Saha', category: 'Şekil', description: 'Orta sahanın dar eşkenar formasyonu. Merkezi kontrol ve hızlı kombinasyonlar sağlar.', detailed_explanation: 'Eşkenar dörtgen orta saha (örnek 4-1-2-1-2). Merkez kontrolü maksimum. Dar alanda hızlı kombinasyonlar. Atalanta Gasperini\'nin özel sistemi. Pas seçenekleri çok fazla.', principles: JSON.stringify(['Eşkenar yapı', 'Merkez kontrolü', 'Hızlı kombinasyon', 'Çok pas seçeneği', 'Kompakt yapı']), how_to_implement: 'Orta sahayı eşkenar dörtgen yap. Dar konumlanma. Hızlı paslaşma. Kanatlardan tam bekler. Merkez ağırlıklı oyun. Kombinasyon futbolu.', required_player_attributes: JSON.stringify(['Teknik yetenek', 'Pas kalitesi', 'Hareket', 'Yaratıcılık', 'Takım uyumu']), suitable_formations: JSON.stringify(['4-1-2-1-2', '4-3-1-2', '4-4-2 eşkenar']), real_world_examples: JSON.stringify(['Atalanta Gasperini', 'Milan Sacchi eşkenar', 'Zeman takımları']), famous_implementations: JSON.stringify(['Gasperini Atalanta', 'Sacchi Milan']), related_concepts: JSON.stringify(['Üçgenler', 'Pozisyonel oyun', 'Merkez kontrolü']), opposing_concepts: JSON.stringify(['Geniş orta saha', 'Kanat ağırlıklı']) },

  { id: 16, concept_name: 'İçe Kesen Bek', category: 'Modern İnovasyon', description: 'Bek oyuncusunun top hakimiyetinde merkeze kayarak orta sahaya katılması. Guardiola devrimı.', detailed_explanation: 'Bek (özellikle tek taraftan) top hakimiyetinde merkeze girer. 3-2 build-up oluşur. Orta sahada sayısal üstünlük. Arsenal Zinchenko, City Cancelo örnekleri. Modern futbolun en önemli yeniliği.', principles: JSON.stringify(['Bek merkeze kayar', '3-2 yapı oluşur', 'Orta saha üstünlüğü', 'Kanatçı geniş kalır', 'Dinamik pozisyonlar']), how_to_implement: 'Bir beki (genelde sol) merkeze al. Kanatçı geniş kalsın. 3-2-5 veya 3-2-4-1 oluştur. Rakibin orta sahasını sayıca ez. Guardiola öğretisi.', required_player_attributes: JSON.stringify(['Pas yeteneği', 'Taktik anlayış', 'Teknik', 'Zeka', 'Versatilite']), suitable_formations: JSON.stringify(['4-3-3', '4-2-3-1', 'Guardiola sistemleri']), real_world_examples: JSON.stringify(['Zinchenko Arsenal', 'Cancelo Man City', 'Lahm Bayern Guardiola']), famous_implementations: JSON.stringify(['Guardiola Man City/Arsenal', 'Arteta Arsenal 2024']), related_concepts: JSON.stringify(['Pozisyonel oyun', 'Sayısal üstünlük', '3-2 build-up']), opposing_concepts: JSON.stringify(['Klasik bekler', 'Statik pozisyonlar']) },

  { id: 17, concept_name: 'Yalancı 9', category: 'Hücum Rolü', description: 'Santraforun derine inmesi, boşluğa orta saha ve kanatçıların akması. Messi\'nin ikonlaştırdığı rol.', detailed_explanation: 'Klasik santrafor yerine derine inen yaratıcı oyuncu. Boşluğa kanat ve orta saha oyuncuları akar. Rakip stoperleri kararsız bırakır. Messi 2009-2012 bu rolde efsane oldu.', principles: JSON.stringify(['Forvet derine iner', 'Boşluğa diğerleri akar', 'Stoperleri kararsız bırak', 'Yaratıcılık', 'Hareket ve boşluk']), how_to_implement: 'Teknik ve yaratıcı bir 10 numarayı forvet pozisyonuna koy. Derine insin, pas dağıtsın. Kanatlardan içe kesme. Orta saha oyuncuları da boşluğa akıtalım.', required_player_attributes: JSON.stringify(['Yaratıcılık', 'Pas', 'Dribling', 'Bitiricilik', 'Topsuz hareket']), suitable_formations: JSON.stringify(['4-3-3 false 9', '4-2-3-1 varyasyonu']), real_world_examples: JSON.stringify(['Messi Barcelona 2009-2012', 'Firmino Liverpool', 'Benzema Real Madrid']), famous_implementations: JSON.stringify(['Guardiola Barcelona Messi', 'Klopp Liverpool Firmino']), related_concepts: JSON.stringify(['Pozisyonel rotasyon', 'Yaratıcı hücum', 'Topsuz koşular']), opposing_concepts: JSON.stringify(['Klasik hedef adam', 'Statik forvet']) },

  { id: 18, concept_name: 'Build-up Oyunu', category: 'Top Hakimiyeti', description: 'Arkadan topu kontrollü şekilde ilerletme ve organize hücum kurma süreci.', detailed_explanation: 'Kaleciden başlayarak kademeli top ilerletme. Sabırlı, riske girmeden. Rakibi çekerek boşluk arama. Modern futbolda kaleci de build-up\'ın parçası. Guardiola ve De Zerbi uzmanları.', principles: JSON.stringify(['Kaleciden başla', 'Sabırlı ilerleme', 'Risk minimize', 'Rakibi çek', 'Boşluk ara']), how_to_implement: 'Kaleci ayakla iyi olmalı. Defans pas yapabilmeli. Orta saha desteğe gelmeli. Kademeli ilerleme. Rakip baskıyı çekerek boşluk aç. Sonra hızlı geçiş.', required_player_attributes: JSON.stringify(['Pas yeteneği', 'Sakinlik', 'Teknik', 'Pozisyon alma', 'Görüş alanı']), suitable_formations: JSON.stringify(['4-3-3', '3-2-4-1', 'Modern sistemler']), real_world_examples: JSON.stringify(['Man City build-up mükemmel', 'Arsenal Arteta build-up', 'Brighton De Zerbi build-up']), famous_implementations: JSON.stringify(['Guardiola takımları', 'De Zerbi Brighton/Marseille']), related_concepts: JSON.stringify(['Pozisyonel oyun', 'Oyun kuran kaleci', 'Sabırlı top hakimiyeti']), opposing_concepts: JSON.stringify(['Uzun top', 'Direkt oyun']) },

  { id: 19, concept_name: 'Bölgesel Savunma', category: 'Savunma', description: 'Oyuncular adamları değil, belirli sahaönlerini savunur. Modern savunmanın standardı.', detailed_explanation: 'Her oyuncu bir bölgeden sorumlu. O bölgeye gelen herkesi savunur. Organize ve sistemik. Modern futbolun savunma standardı. Adam adama savunmadan daha etkili ve yorucu değil.', principles: JSON.stringify(['Bölge sorumluluğu', 'Adam değil alan savun', 'Organize yapı', 'Takım savunması', 'Boşlukları kapat']), how_to_implement: 'Sahayı bölgelere ayır. Her oyuncuya bölge ver. O bölgeye gelen her rakibi savunsun. Kompakt kal. Boşluklar yok. Antrenmanlarla pekiştir.', required_player_attributes: JSON.stringify(['Disiplin', 'Pozisyon alma', 'Takım çalışması', 'Taktik anlayış', 'Konsantrasyon']), suitable_formations: JSON.stringify(['Tüm modern sistemler']), real_world_examples: JSON.stringify(['Çoğu modern takım', 'Guardiola sistemleri', 'Simeone takımları']), famous_implementations: JSON.stringify(['Sacchi Milan bölgesel savunma']), related_concepts: JSON.stringify(['Kompaktlık', 'Organize savunma', 'Pressing']), opposing_concepts: JSON.stringify(['Adam adama savunma', 'Man-marking']) },

  { id: 20, concept_name: 'Adam Adama Savunma', category: 'Savunma', description: 'Her savunma oyuncusu belirli bir rakip oyuncuyu maç boyunca takip eder.', detailed_explanation: 'Her savunmacı bir rakip oyuncuyu sürekli markalar. Eski usul ama bazı durumlarda etkili. Yorucu ve riskli. Bielsa gibi teknik direktörler hala kullanıyor.', principles: JSON.stringify(['Her savunmacı bir rakibi markalar', 'Sürekli takip', 'Birebir sorumluluk', 'Yüksek yoğunluk', 'Riskli ama etkili']), how_to_implement: 'Her defans oyuncusuna rakipten biri ver. Maç boyunca o adamı takip etsin. Yüksek kondisyon gerekli. Disiplin şart. Bazı rakiplere karşı çok etkili.', required_player_attributes: JSON.stringify(['Kondisyon', 'Disiplin', 'Agresiflik', 'Dayanıklılık', 'Konsantrasyon']), suitable_formations: JSON.stringify(['3-3-3-1 Bielsa', '4-3-3 yüksek']), real_world_examples: JSON.stringify(['Bielsa takımları', 'Eski İtalyan futbolu', 'Bazı Güney Amerika takımları']), famous_implementations: JSON.stringify(['Bielsa Leeds', 'Eski Milan takımları']), related_concepts: JSON.stringify(['Yüksek pressing', 'Yoğun savunma']), opposing_concepts: JSON.stringify(['Bölgesel savunma', 'Organize blok']) },

  { id: 21, concept_name: 'Geçiş Anları', category: 'Geçiş', description: 'Top el değiştirdiği 5-10 saniyelik kritik anlar. Modern futbolun en önemli fazı.', detailed_explanation: 'Top kaybında veya kazanımında ilk 5-10 saniye. En kritik an. Gegenpressing veya hızlı kontra. Maçın kazanıldığı veya kaybedildiği an. Klopp ve Guardiola\'nın temel prensibi.', principles: JSON.stringify(['İlk 5-10 saniye kritik', 'Hemen reaksiyon', 'Takım koordinasyonu', 'Agresiflik veya hız', 'Karar verme']), how_to_implement: 'Top kaybında anında baskı (gegenpressing). Top kazanımında hızla ileri (kontra). Otomatik reaksiyonlar. Antrenmanlarla şartlandırma. Kondisyon çok önemli.', required_player_attributes: JSON.stringify(['Kondisyon', 'Hız', 'Karar verme', 'Yoğunluk', 'Takım bilinci']), suitable_formations: JSON.stringify(['Tüm modern sistemler']), real_world_examples: JSON.stringify(['Klopp Liverpool geçişler', 'Guardiola City geçişler', 'Ancelotti Madrid kontralar']), famous_implementations: JSON.stringify(['Klopp takımları', 'Guardiola takımları']), related_concepts: JSON.stringify(['Gegenpressing', 'Kontra atak', 'Yüksek yoğunluk']), opposing_concepts: JSON.stringify(['Organize savunmaya geçiş', 'Düşük tempolu oyun']) },

  { id: 22, concept_name: 'Dinlenim Savunması', category: 'Savunma', description: 'Hücum sırasında bile belirli oyuncuların savunma pozisyonlarını koruması. Kontraya karşı sigorta.', detailed_explanation: 'Hücumda bile bazı oyuncular (genelde pivot ve stopper) pozisyonlarını korur. Ani top kaybında kontraya karşı korunma. Dengeyi sağlar. Mourinho ve Ancelotti\'nin temel prensibi.', principles: JSON.stringify(['Hücumda bile pozisyon koru', 'Pivot ve stoperler geride', 'Kontraya karşı sigorta', 'Denge', 'Organize geri dönüş']), how_to_implement: 'Orta saha oyuncularından en az birisini (pivot) geride bırak. Stoperler çok yukarı çıkmasın. Hızlı geri dönüş için hazır pozisyonlar. Dengeyi koru.', required_player_attributes: JSON.stringify(['Disiplin', 'Pozisyon alma', 'Hız (geri dönüş için)', 'Taktik anlayış', 'Konsantrasyon']), suitable_formations: JSON.stringify(['4-3-3', '4-2-3-1', 'Çift pivot sistemleri']), real_world_examples: JSON.stringify(['Real Madrid Casemiro dinlenim', 'Arsenal Partey/Rice geride', 'Chelsea Kante klasik']), famous_implementations: JSON.stringify(['Mourinho takımları', 'Ancelotti Madrid']), related_concepts: JSON.stringify(['Denge', 'Organize savunma', 'Kontraya karşı koruma']), opposing_concepts: JSON.stringify(['Tam hücum', 'Tüm takım öne']) },

  { id: 23, concept_name: 'Ortalama ve Geri Çevirme', category: 'Hücum', description: 'Kanatlardan ortalama ve ceza sahası önünden geri çevirme pasları. Gol yüzdesi yüksek.', detailed_explanation: 'Yan çizgiden ortalama veya kale çizgisinden geri pas. En yüksek gol yüzdesi olan oyunlar. Liverpool ve Bayern Munich uzmanları. Cutback oyunları son yılların trendi.', principles: JSON.stringify(['Kanatlardan ortalama', 'Geri çevirme pasları (cutback)', 'Yüksek gol yüzdesi', 'İyi timing', 'Koşucu oyuncular']), how_to_implement: 'Kanatçılar yan çizgiye kadar gitsin. Ceza sahasına orta veya geri pas. Orta saha oyuncuları ceza sahasına koşsun. Arsenal ve Liverpool\'un ekmek parası.', required_player_attributes: JSON.stringify(['Orta yeteneği', 'Timing', 'Koşu', 'Bitiricilik', 'Pozisyon alma']), suitable_formations: JSON.stringify(['4-3-3', '4-2-3-1', 'Kanat ağırlıklı sistemler']), real_world_examples: JSON.stringify(['Liverpool Robertson-TAA ortalama', 'Bayern Gnabry-Sane cutback', 'Arsenal Saka geri çevirme']), famous_implementations: JSON.stringify(['Klopp Liverpool', 'Flick Bayern']), related_concepts: JSON.stringify(['Kanat oyunu', 'Ceza sahası koşuları', 'Genişlik']), opposing_concepts: JSON.stringify(['Merkez ağırlıklı hücum', 'Dar oyun']) },

  { id: 24, concept_name: 'Ara Paslar ve Penetrasyon', category: 'Paslaşma', description: 'Savunma hatları arasına veya arkasına keskin paslar. En tehlikeli pas türü.', detailed_explanation: 'Defans ile orta saha veya orta saha ile hücum arasına keskin paslar. En tehlikeli pas. De Bruyne, Odegaard, Bruno uzmanları. Zamanlama ve pas kalitesi kritik.', principles: JSON.stringify(['Hatlar arasına pas', 'Keskin ve direkt', 'Zamanlama kritik', 'Pas kalitesi', 'Koşucu gerekli']), how_to_implement: 'Oyun kuruculara ara pasları aramaları talimatı. Forvetler hatlar arasına koşsun. Timing çok önemli. Pas kalitesi şart. Antrenman antrenman antrenman.', required_player_attributes: JSON.stringify(['Pas yeteneği', 'Vizyon', 'Timing', 'Teknik', 'Cesaret']), suitable_formations: JSON.stringify(['4-3-3', '4-2-3-1', '3-4-3']), real_world_examples: JSON.stringify(['De Bruyne Man City ara pasları', 'Odegaard Arsenal penetrasyon', 'Bruno Fernandes United']), famous_implementations: JSON.stringify(['Guardiola takımları', 'Arteta Arsenal']), related_concepts: JSON.stringify(['Dikey paslaşma', 'Yarı alanlar', 'Üçüncü adam']), opposing_concepts: JSON.stringify(['Yatay paslaşma', 'Güvenli oyun']) },

  { id: 25, concept_name: 'Baskı Tetikleyicileri', category: 'Savunma', description: 'Belirli durumlar oluştuğunda takımın baskıya başlamasını tetikleyen sinyaller.', detailed_explanation: 'Rakip geri pas yaptığında, zayıf ayağına top geldiğinde, yan çizgiye yakınken... Bu durumlarda takım anında baskıya. Otomatik reaksiyonlar. Antrenmanlarla şartlandırma.', principles: JSON.stringify(['Belirli durumlarda otomatik baskı', 'Geri pas tetikleyicisi', 'Yan çizgi tetikleyicisi', 'Zayıf ayak tetikleyicisi', 'Takım koordinasyonu']), how_to_implement: 'Tetikleyicileri belirle (geri pas, yan çizgi, zayıf ayak). Oyuncular bu durumları görünce otomatik baskıya başlasın. Antrenmanlarla otomatik hale getir.', required_player_attributes: JSON.stringify(['Disiplin', 'Konsantrasyon', 'Hız', 'Takım çalışması', 'Kondisyon']), suitable_formations: JSON.stringify(['Pressing sistemleri', '4-3-3', '4-2-3-1']), real_world_examples: JSON.stringify(['Liverpool Klopp tetikleyicileri', 'Man City pressing triggers', 'Arsenal Arteta baskı']), famous_implementations: JSON.stringify(['Klopp Liverpool', 'Guardiola City']), related_concepts: JSON.stringify(['Gegenpressing', 'Baskı tuzakları', 'Organize pressing']), opposing_concepts: JSON.stringify(['Pasif savunma', 'Düşük blok']) },

  { id: 26, concept_name: 'Koridor Oyunu', category: 'Hücum', description: 'Kanat çizgisi ile bek arasındaki dar koridorda yaratılan tehlike. Çapraz koşularla kullanılır.', detailed_explanation: 'Bek ile yan çizgi arasındaki koridor. Bu alanda çapraz koşular çok tehlikelidir. İç kanat + kanat bek kombinasyonu. Arsenal Saka-White, City Bernardo-Walker örnekleri.', principles: JSON.stringify(['Bek ile yan çizgi arası', 'Çapraz koşular', 'İç kanat + kanat bek', 'Dar alanda tehlike', 'Hızlı kombinasyon']), how_to_implement: 'Kanat beki ve iç kanadı bu koridorda kombinasyon yapsın. Çapraz koşular. Biri içe keserken diğeri koridora. Overlap ve underlap.', required_player_attributes: JSON.stringify(['Hız', 'Timing', 'Kombinasyon', 'Dribling', 'Anlayış']), suitable_formations: JSON.stringify(['4-3-3', '4-2-3-1', '3-4-3']), real_world_examples: JSON.stringify(['Arsenal Saka-White koridoru', 'City Bernardo-Walker', 'Liverpool Salah-TAA']), famous_implementations: JSON.stringify(['Arteta Arsenal', 'Guardiola City']), related_concepts: JSON.stringify(['Overlaplar', 'Çapraz koşular', 'Kanat oyunu']), opposing_concepts: JSON.stringify(['Merkez ağırlıklı', 'Statik kanat']) },

  { id: 27, concept_name: 'Savunma Hattı Yüksekliği', category: 'Savunma', description: 'Savunma hattının kaleye olan uzaklığı. Modern futbolda gittikçe yükseliyor.', detailed_explanation: 'Savunma hattı ne kadar yüksek? 2024\'te ortalama 48m (2018\'de 42m idi). Postecoglou Tottenham 52m ile rekortmen. Yüksek hat = daha fazla alan kontrolü ama kontra riski.', principles: JSON.stringify(['Hat yüksekliği stratejik karar', 'Yüksek = alan kontrolü', 'Düşük = güvenlik', 'Ofsayt tuzağı yüksek hatta', 'Hızlı stopper gerekli yüksekte']), how_to_implement: 'Stoperlerin hızını değerlendir. Yüksek hat istiyorsan hızlı stopper şart. Ofsayt tuzağı kullan. Alan kontrolü kazan. Ama kontraya dikkat.', required_player_attributes: JSON.stringify(['Hız (stoperler)', 'Takım koordinasyonu', 'Disiplin', 'Cesaret', 'Pozisyon alma']), suitable_formations: JSON.stringify(['Modern sistemler', '4-3-3 yüksek', '3-4-3']), real_world_examples: JSON.stringify(['Postecoglou Spurs en yüksek', 'Arsenal yüksek hat', 'Liverpool Klopp yüksek']), famous_implementations: JSON.stringify(['Postecoglou Tottenham', 'Guardiola sistemleri']), related_concepts: JSON.stringify(['Ofsayt tuzağı', 'Yüksek pressing', 'Alan kontrolü']), opposing_concepts: JSON.stringify(['Düşük blok', 'Derin savunma']) },

  { id: 28, concept_name: 'Dinamik Rotasyonlar', category: 'Hareket', description: 'Oyuncuların pozisyonlarını sürekli değiştirerek rakibi şaşırtması ve boşluk yaratması.', detailed_explanation: 'Oyuncular pozisyonlarını sürekli değiştirir. Kanatçı merkeze, santrafor kanada, bek öne... Rakip markaj şaşırır. Boşluklar açılır. Guardiola ve De Zerbi sistemlerinin özü.', principles: JSON.stringify(['Sürekli pozisyon değişimi', 'Akışkan şekil', 'Rakibi şaşırt', 'Boşluklar yarat', 'Zeka gerektir']), how_to_implement: 'Oyunculara rotasyon özgürlüğü ver. Ama yapısal dengeyi koru. Birisi çıkınca diğeri yerine geçsin. Antrenmanlarla pekiştir. Zeka ve anlayış gerekli.', required_player_attributes: JSON.stringify(['Zeka', 'Versatilite', 'Taktik anlayış', 'Takım uyumu', 'Teknik']), suitable_formations: JSON.stringify(['4-3-3 akışkan', 'Guardiola sistemleri', 'De Zerbi sistemleri']), real_world_examples: JSON.stringify(['Guardiola Man City sürekli rotasyon', 'De Zerbi Brighton akışkan', 'Arsenal Arteta rotasyonları']), famous_implementations: JSON.stringify(['Guardiola takımları', 'De Zerbi Brighton']), related_concepts: JSON.stringify(['Pozisyonel oyun', 'Akışkan hücum', 'Taktik esneklik']), opposing_concepts: JSON.stringify(['Sabit pozisyonlar', 'Statik şekil']) },

  { id: 29, concept_name: 'Duran Top Rutinleri', category: 'Duran Toplar', description: 'Korner, serbest vuruş ve taçlarda önceden planlanmış oyun şemaları. Gollerin %30\'u buradan.', detailed_explanation: 'Duran toplarda planlanmış koşular ve pozisyonlar. Gollerin %30\'u buradan gelir. Arsenal 2024 duran top makinesi. Antrenmanlarla mükemmelleştirme. Çok önemli ama ihmal edilen alan.', principles: JSON.stringify(['Planlanmış rutinler', 'Antrenman gerektir', 'Koşular ve bloklar', 'Gol yüzdesi yüksek', 'Varyasyonlar önemli']), how_to_implement: 'Duran top antrenmanları yap. Farklı rutinler geliştir. Koşular, bloklar, aldatmacalar. Varyasyonlar hazırla. Arsenal buna saatler harcıyor.', required_player_attributes: JSON.stringify(['Fiziksel güç', 'Kafayla kuvvetli', 'Timing', 'Koordinasyon', 'Disiplin']), suitable_formations: JSON.stringify(['Tüm sistemler']), real_world_examples: JSON.stringify(['Arsenal 2024 duran top kralı', 'Liverpool korner rutinleri', 'Man City yaratıcı duran toplar']), famous_implementations: JSON.stringify(['Arteta Arsenal', 'Stoke City Tony Pulis dönemi']), related_concepts: JSON.stringify(['Fiziksel üstünlük', 'Koşular', 'Bloklamalar']), opposing_concepts: JSON.stringify(['Bölge savunması duran top', 'Adam adama duran top']) },

  { id: 30, concept_name: 'Savunma Örtü ve Dengesi', category: 'Savunma', description: 'Takım arkadaşlarını örtüleme ve dengeyi koruma. Bir savunmacı atlatıldığında diğeri örtüler.', detailed_explanation: 'Bir defans oyuncusu atlatıldığında takım arkadaşı örtüler. Sürekli destek ve denge. İtalyan savunmasının DNA\'sı. Maldini-Baresi örtüleme örneği efsanedir.', principles: JSON.stringify(['Takım arkadaşını örtüle', 'Sürekli destek pozisyonu', 'Denge koru', 'Boşlukları kapat', 'Koordinasyon']), how_to_implement: 'Savunmacılar birbirlerini örtüsün. Biri baskıya çıkınca diğeri örtüye. Üçgen pozisyonlar. Boşluk bırakma. İtalyan takımlarını izle.', required_player_attributes: JSON.stringify(['Pozisyon alma', 'Takım çalışması', 'Disiplin', 'Öngörü', 'Hız']), suitable_formations: JSON.stringify(['Tüm sistemler', 'Özellikle İtalyan tarzı']), real_world_examples: JSON.stringify(['İtalyan takımları klasik', 'Chelsea Mourinho dönemi', 'Atletico Simeone']), famous_implementations: JSON.stringify(['İtalyan takımları', 'Mourinho sistemleri']), related_concepts: JSON.stringify(['Bölgesel savunma', 'Organize savunma', 'Kompaktlık']), opposing_concepts: JSON.stringify(['Bireysel savunma', 'Adam adama']) },

  { id: 31, concept_name: 'Dikey Kompaktlık', category: 'Savunma', description: 'Hatlar arasındaki dikey mesafeyi minimize etme. 25-30m ideal mesafe.', detailed_explanation: 'Savunma, orta saha, hücum hatları arasında 25-30m mesafe. Dikey olarak sıkı kal. Rakibe hatlar arasında boşluk verme. Kompaktlığın dikey versiyonu. Pressing sistemlerinde kritik.', principles: JSON.stringify(['Hatlar arası 25-30m', 'Dikey sıkılık', 'Boşluk verme', 'Birlikte hareket', 'Organize yapı']), how_to_implement: 'Hatlar birlikte hareket etsin. Savunma çıkarsa orta saha da çıksın. Hücum geri geldiğinde herkes geri. Dikey mesafeyi 25-30m tut. Pressing yapıyorsan daha da sıkı.', required_player_attributes: JSON.stringify(['Disiplin', 'Kondisyon', 'Takım çalışması', 'Taktik anlayış', 'Pozisyon alma']), suitable_formations: JSON.stringify(['Tüm modern sistemler', 'Pressing sistemleri']), real_world_examples: JSON.stringify(['Pressing yapan tüm takımlar', 'Liverpool Klopp kompakt', 'Atletico Simeone sıkı']), famous_implementations: JSON.stringify(['Klopp takımları', 'Simeone Atletico']), related_concepts: JSON.stringify(['Kompaktlık', 'Pressing', 'Organize savunma']), opposing_concepts: JSON.stringify(['Uzun mesafeler', 'Dağınık şekil']) }
];

let completed = 0;
let failed = 0;

function translateConcept(concept) {
  return new Promise((resolve) => {
    const sql = `UPDATE tactical_concepts SET
      concept_name = ?,
      category = ?,
      description = ?,
      detailed_explanation = ?,
      principles = ?,
      how_to_implement = ?,
      required_player_attributes = ?,
      suitable_formations = ?,
      real_world_examples = ?,
      famous_implementations = ?,
      related_concepts = ?,
      opposing_concepts = ?
      WHERE id = ?`;

    db.run(sql, [
      concept.concept_name,
      concept.category,
      concept.description,
      concept.detailed_explanation,
      concept.principles,
      concept.how_to_implement,
      concept.required_player_attributes,
      concept.suitable_formations,
      concept.real_world_examples,
      concept.famous_implementations,
      concept.related_concepts,
      concept.opposing_concepts,
      concept.id
    ], (err) => {
      if (err) {
        console.log(`❌ ID ${concept.id} çevrilemedi:`, err.message);
        failed++;
      } else {
        console.log(`✅ ID ${concept.id} - ${concept.concept_name} Türkçeye çevrildi`);
        completed++;
      }
      resolve();
    });
  });
}

async function translateAll() {
  for (const concept of turkishConcepts) {
    await translateConcept(concept);
  }

  console.log(`\n✅ KALAN 23 KONSEPT ÇEVRİLDİ!`);
  console.log(`   Başarılı: ${completed}`);
  console.log(`   Başarısız: ${failed}`);
  console.log(`\n🎉 TOPLAM 31 TACTICAL CONCEPT ARTIK TAMAMEN TÜRKÇE!\n`);

  db.close();
}

translateAll();
